### ISSUE TITLE
Submission for SC consideration: PEP 680 -- tomllib

### ISSUE THREAD

**Issue by hukkin** [python/steering-council#104]
Dear SC, please consider [PEP 680 -- tomllib: Support for Parsing TOML in the Standard Library](https://www.python.org/dev/peps/pep-0680/)

The PEP has been discussed here: https://discuss.python.org/t/13040

A quick summary of the discussion (credit goes to @hauntsaninja):
- Anticipated concerns about module name and the lack of write API
- Discussion of `parse_float` keyword argument, with followup PR here: https://github.com/python/peps/pull/2278
- Discussion of loading binary files vs text files. PR to help make reasoning more clear here: https://github.com/python/peps/pull/2281

cc @hauntsaninja @encukou

**Comment by brettcannon** [comment]
Thanks, added to our agenda!

**Comment by encukou** [comment]
The PEP was [accepted](https://mail.python.org/archives/list/python-dev@python.org/thread/3AHGWYY562HHO55L4Z2OVYUFZP5W73IS/).
