### ISSUE TITLE
Submission for SC consideration: PEP 675 -- Arbitrary Literal String Type

### ISSUE THREAD

**Issue by pradeep90** [python/steering-council#108]
Please consider PEP 675 for inclusion in Python 3.11. This is primarily of interest to users of static type checkers. It introduces a supertype for precise literal string types, such as `Literal["foo"]`, called `LiteralString`.

The PEP has been discussed at length in typing-sig ([thread 1](https://mail.python.org/archives/list/typing-sig@python.org/thread/JJWAA5AHZ4I6MCS26J3IJLJ7RW4PWUMA/#SP3VBXH5BVFBZRWRVDUK6SUNDQ7DFYGE), [thread 2](https://mail.python.org/archives/list/typing-sig@python.org/thread/VB74EHNM4RODDFM64NEEEBJQVAUAWIAW/)) and on the [draft doc](https://docs.google.com/document/d/1fbAbA2MCoAcSO1c8gecmUJYZ-Q0utT3CmaXlQ3IhzZw/edit?usp=sharing). We have also notified [python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/AXR3ZBEZF2UTBC2RFCASBTQB4ZYNQGET/). There is also a [Reddit thread](https://www.reddit.com/r/Python/comments/r71lzi/pep_675_arbitrary_literal_strings/) and a BPO [issue](https://bugs.python.org/issue46200) mentioning the PEP.

We have a reference implementation of the type checking part in Pyre and an implementation of the `LiteralString` special form in `typing_extensions.py` ([PR](https://github.com/python/typing/pull/1053)).

CC: @gbleaney @JelleZijlstra

https://www.python.org/dev/peps/pep-0675/

**Comment by encukou** [comment]
Thanks! I added it to the agenda.
