### ISSUE TITLE
 PEP 587 "Python Initialization Configuration" is ready for pronouncement

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#11]
Hi,

First of all, Brett Cannon selected Thomas Wouters @Yhg1s as the BDFL-delegate for my PEP 587. But I'm opening an issue for the Steering Committee anyway, because I'm out of time: next week, I will be off between May 30 and June 2, whereas the deadline for Python 3.8 feature freeze is at May 31 (2019-05-31).

In discussions, I saw Nick Coghlan, Brett Cannon and Barry Warsaw quite happy with the overall design. So I don't expect too much controverse :-) Hopefully, every tiny detail has been discussed to death on python-dev :-)

My PEP 587 is at the version 4. I got more feedback and so I am working on a 5th version:
https://github.com/vstinner/peps/pull/1/files

The 5th version is basically ready to be merged. But. I would prefer to not have a 6th version, mostly because I don't have time anymore :-) So I would prefer a review before merging it and I hope that the 5th version can be approved directly!

The overall design is the PEP 432 which is discussed since the end of 2012. The design and rhe mplementation of my PEP 587 is being discussed since July 2018 (see the Discussions section of my PEP). Users had plenty of time to provide feedback, and thanks to that, I was able to mature my API a lot very quickly!

I read again all previous discussions related to this PEP to ensure that all concerns are now taken in account. I was surprised by the high number of issues which are solved by my PEP. I'm talking about issues listed by users in discussions, but also the "Python Issues" section of my PEP.

Points which are not not addressed by my PEP:

* By default, the path configuration is still automatically computed by Modules/getpath.c and PC/getpathp.c which are implemented in C. The configuration files are still used by default to compute the path configuration. This part is underspecified but I chose to not address it with my PEP, mostly because I didn't have enough time to work on this topic. **But** my PEP allows to completely override the path configuration and omits this function computing it.

* It is not possible to modify PyConfig between Core and Main configuration phases in Python. It was a request of Steve Dower to easily reimplement the function computing path configuration in Python. Technically, it would take me less than one hour to add 2 functions to read and write the configuration. But I'm just too busy to experiment this, update the PEP, etc.

I tried hard to not expose the multi-phase initialization ("Core" and "Main" phases), but I got too much pressure from users, and so I decided to put it finally in the 5th version of my PEP. This API comes with a very explicitly warning: the proposed API is both **private** and **provisional**. Extract of the PEP:

> the API can be modified or even be removed anytime until a proper public API is design

I chose to put the API at part of the PEP since it's a common and popular request, but also because it will allow us to get real feedback from users.

The documentation of the PyConfig and the Path Configuration is a work-in-progress. I plan to complete it before Python 3.8 final in the actual implementation.

Even if the PEP is approved, I still expect minor changes in the default PyPreConfig and PyConfig configurations, mostly to adjust the implementation or fix bugs. This default configurations is hard to design, but at least it now has a complete and mature test suite (Lib/test/test_embed.py and Programs/_testembed.c)!

Reminder: the whole PEP 587 is already implemented in the master branch, the PEP is only about making the API public :-)

Note: I spent so much time on the implementation and in the design of the PEP over the two last years, I would be sad if the API miss Python 3.8 deadline :-( We already missed 3.7 deadline, but that was a good thing: the implementation was far from being ready :-) (and the API was non-existent!)

**Comment by brettcannon** [comment]
@vstinner  With @yhg1s as BDFL-Delegate I'm not sure what you're specifically asking of the steering council? If Thomas approves the PEP in time and you can get it committed (or sign-off from the RM) then it can be in 3.8, but I don't see where the SC fits into this.

**Comment by Yhg1s** [comment]
On Fri, May 24, 2019 at 12:14 AM Brett Cannon <notifications@github.com>
wrote:

> @vstinner <https://github.com/vstinner> With @Yhg1s
> <https://github.com/Yhg1s> as BDFL-Delegate I'm not sure what you're
> specifically asking of the steering council? If Thomas approves the PEP in
> time and you can get it committed (or sign-off from the RM) then it can be
> in 3.8, but I don't see where the SC fits into this.
>
Let's short-cut this: I'll happily accept version 5 of the PEP, once it's
submitted. It's clearly an improvement fixing many existing issues, the
main objections are asking for much more extensive changes that aren't
going to land in one go (and may not be feasible), we can bike-shed over
exact names of functions after b1, and while it introduces two new concepts
(PyInitStatus and PyWideStringList) they make sense for the specific
use-case, and won't be in the way of further development. (I imagine more
uses of PyInitStatus, tbh.)

When you're ready, Victor, submit version 5 and I'll send a message to
python-dev.

-- 
Thomas Wouters <thomas@python.org>

Hi! I'm an email virus! Think twice before sending your email to help me
spread!

**Comment by brettcannon** [comment]
@Yhg1s thanks for that follow-up! I'm going to close this then as resolved and not directly under the steering council's purview ATM.
