### ISSUE TITLE
Submission for SC consideration: PEP 682 -- Format Specifier for Signed Zero 

### ISSUE THREAD

**Issue by belm0** [python/steering-council#110]
https://python.github.io/peps/pep-0682/

https://discuss.python.org/t/pep-682-format-specifier-for-signed-zero/13596

Thank you!

**Comment by encukou** [comment]
I've added it to the agenda.

**Comment by gpshead** [comment]
Hi, we (the steering council) discussed this PEP briefly yesterday and decided the concept makes sense but that we'd all defer to Mark Dickinson as the domain expert to decide here anyways. So if @mdickinson doesn't object to the role (he's already the PEP sponsor), Mark can decide.
