### ISSUE TITLE
SC Review: Changes to PEP 1 to reflect current best practice on PEP announcement, discussion and resolution

### ISSUE THREAD

**Issue by CAM-Gerlach** [python/steering-council#113]
As discussed with PEP editors/SC members @encukou , @warsaw and others on python/peps#2266 , PEP 1 does not reflect current real-world accepted practice when it comes to the technical and administrative aspects of announcing, discussing, submitting and pronouncing on PEPs, which has resulted in confusion and missteps from both PEP writers and readers consulting it for guidance. We intend to update the language in PEP 1 (and a few small relevant parts of PEP 12 and the template) to reflect present real-world best practice by the SC and community in these areas, in order to clarify the current process, improve the experience for PEP authors, the SC/delegates and the community, and avoid confusion, uncertainty and mistakes around these points, and update/remove related out of date content that no longer accurately reflects the de jure or de facto state.

This was then implemented in python/peps#2346 ; as part of this change, we re-organize the various scattered, sometimes duplicative or even contradictory paragraphs discussing PEP discussion, announcement and similar into one coherent section, with a clearer, more sequential and logical ordering of the overall process, and adds additional clarifying detail and guidance on points that were previously considered implicit or not referred to at all. Additionally, we provide additional clarity on the time and process to submit a PEP for SC consideration (another major point of confusion for some of the recent PEP author situations that motivated this change) where related to the above changes, though we look to further improve this in a future PR (as the current text seems to state that all PEPs must have a PEP-Delegate, or be deferred, which is hardly the case in the present day).

While the changes were generally technical in nature, we were hoping to solicit SC feedback and assent prior to merge, since PEP 1 is an important governance meta-PEP. Unfortunately, due to a miscommunication, the PR was merged prematurely before the intended SC review had been requested. Could the SC look over the changes to ensure they are agreeable, and request any revisions you might like us to implement? Thanks!

**Comment by brettcannon** [comment]
I've added this to our agenda.

**Comment by CAM-Gerlach** [comment]
Additionally, just to note, python/peps#2358 implements a related technical change, which has PEP authors/editors directly inline-link the posted discussion threads to the listed dates in the `Post-History` field, providing a permanent record of past discussions for the consideration of SC members, reviewers, the community and interested readers, resolving a concern (albeit not a regression) previously brought up by @brettcannon and several other community members that the previous `Discussions-To` link would not be recorded when a new thread was posted.

**Comment by brettcannon** [comment]
We talked it over and we're happy with the changes.

**Comment by brettcannon** [comment]
And thanks for bringing to our attention!

**Comment by CAM-Gerlach** [comment]
Happy to, and thanks for the support!
