### ISSUE TITLE
re.RegexFlag enumeration

### ISSUE THREAD

**Issue by ethanfurman** [python/steering-council#114]
From the PEP663 rejection notice:

> Second, we find the PEP’s distinction between global and normal enum values to be highly confusing.  It makes predicting the results more difficult, since the results will differ for the same object depending on where the name it is bound to is defined, and how it is accessed.  To us, this makes understanding what object you are looking at much less clear. There are also not enough precedents for objects that modify their string representation based on where the name is bound.

I was basing my changes on the RegexFlag implementation (contributed by Serhiy in 3.8 I think); what that means now is that, for example, `re.ASCII` has a repr of `re.ASCII` while most other stdlib enums have a repr of, for example, `<SocketKind.SOCK_STREAM: 1>`.

- Do we care about that lack of consistency?
- If we don't, is the repr for stdlib enums decided on a case-by-case basis?

**Comment by brettcannon** [comment]
We are actually discussing this in our SC meeting as I type this.

**Comment by brettcannon** [comment]
We discussed this and we think it's okay for `re.RegexFlag` being different in this specific case since it held its current semantics all the way back to Python 3.8.
