### ISSUE TITLE
PEP 655 -- Marking individual TypedDict items as required or potentially-missing

### ISSUE THREAD

**Issue by davidfstr** [python/steering-council#115]
Hi, PEP 655 is ready for Steering Council review. This PEP introduces new typing qualifiers `Required[]` and `NotRequired[]` to `typing.py` which make it easy to mark individual items of a TypedDict as either required or potentially-missing, without needing to resort to the {total=False, inheritance} trick that can be done with TypedDicts declared with the class-based syntax.

* PEP Text: https://www.python.org/dev/peps/pep-0655/

* Discussions-To: https://mail.python.org/archives/list/typing-sig@python.org/thread/53XVOD5ZUKJ263MWA6AUPEA6J7LBBLNV/

(FYI: This issue was templated off of the recent similar PEP-submission issue #109 )

--
David Foster | Seattle, WA, USA
Contributor to TypedDict, mypy, and Python's typing system

**Comment by brettcannon** [comment]
I've added it to our agenda!

**Comment by gpshead** [comment]
accepted! https://mail.python.org/archives/list/python-dev@python.org/thread/AJEDNVC3FXM5QXNNW5CR4UCT4KI5XVUE/  (my emails hit the moderation queue, that'll show up on typing-sig as well)
