### ISSUE TITLE
Submission for SC consideration: PEP 681 -- Data Class Transforms

### ISSUE THREAD

**Issue by debonte** [python/steering-council#117]
Please consider PEP 681 for inclusion in Python 3.11.

This is a typing PEP that provides a way to describe the behavior of dataclass-like libraries to static type checkers.

The PEP has been discussed at length in several typing-sig threads:

- The primary PEP discussion thread: [Dataclass Transform draft PEP](https://mail.python.org/archives/list/typing-sig@python.org/thread/EAALIHA3XEDFDNG2NRXTI3ERFPAD65Z4/)
- Early pre-PEP discussions:
  - [Supporting dataclass-like semantics](https://mail.python.org/archives/list/typing-sig@python.org/thread/TXL5LEHYX5ZJAZPZ7YHZU7MVFXMVUVWL/#TSYS2J46BPQJVT4C5OVIABCYMHKSQOCF)
  - [Dataclass Transform](https://mail.python.org/archives/list/typing-sig@python.org/thread/NHEYOPDLV745SB5DDU5WRYFMNGGLTXRI/#NHEYOPDLV745SB5DDU5WRYFMNGGLTXRI)
- Threads on specific aspects of the design:
  - [PEP 681: Descriptor fields with dataclass_transform](https://mail.python.org/archives/list/typing-sig@python.org/thread/BW6CB6URC4BCN54QSG2STINU2M7V4TQQ/)
  - [Clarification about PEP 681 statement](https://mail.python.org/archives/list/typing-sig@python.org/thread/GW67GYHTFUMCDBEEHTNUD4PWV2BG3H3C/#JCQ6NPYJUEQMQ4DISXOOTDU4WTLKWWW5)
  - [dataclass_transform support for converter field descriptor parameter](https://mail.python.org/archives/list/typing-sig@python.org/thread/5XZQK7GVIRSYMKWENQFIROMLJKN2QZVU/#7SDEVKQHONDOL5B6DUU7TIHMIA4ASQIR)

We also posted an RFC notification on [discuss.python.org](https://discuss.python.org/t/rfc-on-pep-681-data-class-transforms/14116) pointing to the canonical thread on typing-sig.

There is a reference implementation of the type checking part in [Pyright](https://github.com/microsoft/pyright/blob/main/packages/pyright-internal/src/analyzer/dataClasses.ts), and an implementation of the `dataclass_transform` decorator in [`typing_extensions.py`](https://github.com/python/typing/pull/1054).

CC: @JelleZijlstra @erictraut

https://www.python.org/dev/peps/pep-0681/

**Comment by brettcannon** [comment]
I've added the PEP to our agenda.

**Comment by encukou** [comment]
@gvanrossum & @JelleZijlstra, what is the typing-sig consensus on this?

**Comment by JelleZijlstra** [comment]
I guess we'll start the process you laid out on typing-sig :)

Sentiment has been generally positive but I can send a fuller summary later today after consulting with Guido.

**Comment by JelleZijlstra** [comment]
@gvanrossum and I discussed the PEP today and we recommend accepting it.

Some main points:
* The PEP addresses an important pain point with typing for users of many widely used libraries.
* There has been mostly positive feedback, including from the maintainers of target libraries such as attrs, pydantic, and SQLAlchemy, and also from the maintainers of other type checkers.
* We had some concerns around locking in a feature that is currently specific to Pyright (as far as I can tell, no other type checker has implemented the PEP yet) and may not cover the needs of all libraries. However, the PEP explicitly keeps the door open to add additional customization options in the future, and we have a mechanism (typing-extensions) to distribute such changes to users.

I collected discussion links in python/peps#2502 (both mailing lists and the Pyright issue tracker).

**Comment by erictraut** [comment]
> as far as I can tell, no other type checker has implemented the PEP yet

I think that pyre has also implemented support for it already. @pradeep90 or @shannonzhu could confirm.

**Comment by pradeep90** [comment]
Yes, Pyre has partially implemented dataclass-transform. We support the decorator function and class examples and are yet to handle the metaclass example.

Overall, Pyre is +1 on this PEP as it will save us from maintaining custom support for N dataclass-like frameworks and will automatically enable ones we don't yet support (such as Pydantic).

**Comment by gvanrossum** [comment]
Jelle and I discussed it this morning and I am indeed onboard with this. I hope the SC adopts our recommendation!

**Comment by debonte** [comment]
Sent RFC to python-dev as requested by @brettcannon -- https://mail.python.org/archives/list/python-dev@python.org/thread/7MEB5WYMUZ6SPEVZMVG5H7NQRI7KRB25/

**Comment by brettcannon** [comment]
I have made sure it's back on the agenda (PyCon US + illness + vacation is meant not much has happened since our comments).

**Comment by encukou** [comment]
It's now accepted: https://mail.python.org/archives/list/python-dev@python.org/message/R4A2IYLGFHKFDYJPSDA5NFJ6N7KRPJ6D/
Thank you for your patience!
