### ISSUE TITLE
Add Linux s390x platform to PEP 11 Tier 3

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#122]
When the PEP 11 change (tiered platform support) was discussed recently, I was volunteer to support Linux s390x. I also [proposed to add a Tier 3](https://mail.python.org/archives/list/python-committers@python.org/thread/V3OZPJGA5VJFYM6XYGPZIVPOIYKX6KTD/) **for s390x** (and FreeBSD). But it got lost in the discussion, and the merged PEP 11 change miss it.

I proposed https://github.com/python/peps/pull/2543 to add Linux s390x to Tier 3. I'm volunteer to support it.

I don't have a SSH access to the s390x buildbot workers, but I can get access to different s390x machines using Red Hat infrastructure, Fedora Test Machines, the GCC Compiler Farm, etc.

s390x hardware is (very) expensive, but today it's possible to emulate the architecture in a VM (ex: qemu supports it).

I'm working for Red Hat who supports s390x in its RHEL product, so I have interests to make sure that Python supports well s390x architecture in Fedora and RHEL ;-)

Brett wrote:

> You will need to ask the SC as the PR was what we reviewed and approved.

I'm not sure about the process, so I'm asking here.

PEP 11 says:

> To be promoted to a tier, steering council support is required and is expected to be driven by team consensus. Demotion to a lower tier occurs when the requirements of the current tier are no longer met for a platform for an extended period of time based on the judgment of the release manager or steering council.

There are many s390x buildbot workers:

* Debian
* Fedora Stable
* Fedora Rawhide
* RHEL 7
* RHEL 8

With some Clang, LTO, LTO+PGO and Refleaks variants.

**Comment by gpshead** [comment]
For Tier 3 I'm inclined to approve all core dev platform additions who are volunteering themselves for a platform first and only ask questions later to see if it still makes sense if the volunteer(s) for those are unable to get to anything important in an undefined "reasonable" time frame that people determine causes problems.

**Comment by vstinner** [comment]
> There are many s390x buildbot workers

Oh, I forgot to mention that all of these workers are stable (pass tests for several weeks). s390x Refleaks workers recently did they work by detecting a real regression (I fixed it yesterday).

**Comment by gpshead** [comment]
Discussed, we agree with the additions. Proceed with the PR.
