### ISSUE TITLE
Semi-stable C API tier

### ISSUE THREAD

**Issue by encukou** [python/steering-council#123]
Hi,
I'd like to introduce a subset of the C API that can change in every minor release, without deprecation warnings, for use cases like debuggers and JIT compilers (e.g. PEP-523). We already have API like this, but it's marked as such in inconsistent ways (leading underscores,  notes in docs or in a PEP).
To prevent using it accidentally, it would be opt-in (exposed only by defining `Py_USING_SEMI_STABLE_API`). API that's now public or documented would have a deprecation period of at least *one release* rather than the usual two until this opt-in is mandatory. 
Details are discussed in https://github.com/python/cpython/issues/91744, background is on [python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/MA4FQ7G6F35NG3TUN6RQPXRGXTYMFMDY/#MA4FQ7G6F35NG3TUN6RQPXRGXTYMFMDY)

The bad news is that this API is still changing (e.g. the `PyCode_New` signature changed last week). It will probably be necessary to adjust the semi-stable API in early betas. (I see it as part of stabilization, but views might vary.) It should be as stable as the ABI -- formally in the first RC, but hopefully sooner.

Is the SC OK with this? If yes, how much oversight over details does it want? Does this need a PEP?

*(I added this to the agenda)*

**Comment by gvanrossum** [comment]
I'm confused. You state "can change in every minor release" but also "as stable as the ABI". Those seem wildly different. Which is it? What am I misunderstanding?

**Comment by encukou** [comment]
I'm talking about the regular, version-specific ABI, like `cp310-cp310-manylinux_2_17_x86_64` in wheels. Not the Stable ABI (`abi3`).

**Comment by gvanrossum** [comment]
Thanks; your use of "stable" and "ABI" in the same phrase confused me. ;-)

**Comment by encukou** [comment]
It needs a PEP. I'll write one.
