### ISSUE TITLE
PEP 689 – Unstable C API tier

### ISSUE THREAD

**Issue by encukou** [python/steering-council#125]
Please consider PEP 689 – Unstable C API tier
https://peps.python.org/pep-0689/

I understand it is very late in the Beta cycle, but still hope to include it to make our API compatibility expectations clearer for both users and core devs.
The PEP has been discussed on python-dev: https://mail.python.org/archives/list/python-dev@python.org/thread/PQXSP7E2B6KNXTJ2AERWMKKX42YP5D6O/
Since the first version, the name changed from “semi-stable” to “unstable”, and I included a wording clarification proposed by a PEP editor: https://github.com/python/peps/commit/5232fda0ab13254ce6904987d1f2373cd112c5fa.

**Comment by CAM-Gerlach** [comment]
It would seem this didn't make the cut to be considered for 3.11, now that rc1 is out?

**Comment by encukou** [comment]
There are disagreements about what *currently* marks something as private API, and that needs to be addressed first. I should defer the PEP.
