### ISSUE TITLE
python/typing_extensions repo

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#126]
We're hoping to split the typing_extensions extension module off the python/typing repo, to separate various typing discussions from the code that provides runtime support (mostly so new typing features can be used in old Python versions). See https://github.com/python/typing/issues/1182.

- Do we need permission from the SC for this?
- If not, do we need to ask anyone else for permissions? It *looks* like I have permissions to just create the repo, but I'd rather be safe than sorry.

**Comment by brettcannon** [comment]
I _think_ this falls to the SC to okay, but I honestly can't remember if we have officially said "the Python org on GitHub falls under the SC purview".

I've added this to our agenda, regardless.

**Comment by JelleZijlstra** [comment]
Just for background:
* typing-extensions provides backports of new typing features to old Python versions (e.g., `typing_extensions.Self` for Python <3.11) as well as experimental implementations of features in not-yet-accepted typing PEPs.
* It's maintained by core devs and people involved with typeshed. (I've been doing the releases most recently.)
* It's a very widely used package, in or around the top 10 most frequently downloaded PyPI packages. All type checkers use it.

**Comment by encukou** [comment]
> Do we need permission from the SC for this?

The SC still plans to discuss a general policy.
But in this particular case, there are no objections. Feel free to create the repo!

Thank you for asking!

– Petr, on behalf of the SC

**Comment by encukou** [comment]
*Speaking for myself only:*
Note that the [devguide](https://devguide.python.org/devcycle/?highlight=organization%20admin#organization-repository-policy) covers what kind of repos go in `python`. The SC might want to tweak this text though.
IMO `typing_extensions` is indeed in the "permission should be sought from the SC" territory. 

And: if you lack GitHub permissions for creating the repo, adding members, etc., one of the [owners](https://devguide.python.org/devcycle/?highlight=organization%20admin#current-owners) should be able to sort that out.
