### ISSUE TITLE
Using GitHub Projects to provide insight in what's currently on the SC's table

### ISSUE THREAD

**Issue by erlend-aasland** [python/steering-council#127]
I'm wondering if it would make sense for the SC to start using GitHub Projects to track the status of SC issues. The current status could then be communicated visually, for example using GitHub Projects boards; it would be easy for core devs to, for example, check if their PEP is being discussed, or if it's still on the agenda.

From the top of my head, some tweaks to the default Kanban template should be sufficient:

| Kanban | Tweaked to | Meaning |
| --- | --- | --- |
| No Status | No Status | Not on the agenda (default status) |
| Todo | On the Agenda | The issue has been added to the agenda |
| In Progress | Under Discussion | The issue is being discussed by the SC |
| Done | Done | The SC made some kind of decision |

What do you think? Hopefully, it would not add too much overhead for the SC, and hopefully, it would provide valuable insight for everyone.

**Comment by encukou** [comment]
Thanks, I've added the suggestion to our agenda.

We actually already use a GH Project for the agenda. Making it public would mean we'd need another way to track sensitive issues.

*(Speaking as myself here, without coordinating with the other SC members)*

**Comment by ezio-melotti** [comment]
> We actually already use a GH Project for the agenda. Making it public would mean we'd need another way to track sensitive issues.

Apparently you can have a public project that includes links to issues in a private repo, and the issue will be hidden.

I just did a quick test and added an issue from a private repo to a public project, and this is what I see:
![image](https://user-images.githubusercontent.com/25624924/173031694-58762764-c6ea-4ac4-922b-0e89bb574d76.png)

The same issue (the 12th) is visible when I'm logged in with a user that has access to the private repo:
![image](https://user-images.githubusercontent.com/25624924/173032392-eb2ef203-f099-4804-bb45-5ff0ec3a5199.png)

This would mean having two separate repos though: one for sensitive/private issues, and another for public ones.

**Comment by bskinn** [comment]
If the main thing that would be valuable to have publicly tracked this way would be PEPs, the public project could just reside in python/peps?

**Comment by ezio-melotti** [comment]
Beta projects can only be created at the org level anyway, and then they can be added to repos.  If the project tracks more than just PEPs, a custom field to distinguish the type of item can be created and possibly mapped to different columns in a separate kanban-style view.

If you need help setting up such a project let me know.

**Comment by encukou** [comment]
We don't think we can do this process efficiently with our current workflow, but we'll keep the suggestion in mind for the future.
Thanks for the idea!
