### ISSUE TITLE
Requesting extra privileges to perform administrative tasks

### ISSUE THREAD

**Issue by ezio-melotti** [python/steering-council#128]
In order to perform the migration I was given extra privileges at the org level, which were removed yesterday (see https://github.com/python/devguide/pull/887).  During and after the migration, I've been using these permissions to perform some administrative tasks related to the migration, and over time I (somewhat unknowingly) started using them to perform other administrative tasks [^1].

Now that the permissions have been removed, I find myself unable to perform certain tasks, and I'm therefore requesting for the permissions to be reinstated and possibly for my role as an org admin to be formalized.

Some examples of tasks I've been performing that require org-level permissions:
* Reclaiming mannequin users for new core devs and triagers.
* Adding people to teams when requested on core-workflow (see e.g. https://github.com/python/core-workflow/issues/461, or past issues about adding triagers).
* Blocking users from the org and reporting spam (this happened ~3 times and was done in response to requests made on Discord, the last of which was made yesterday -- GitHub then terminated all those accounts shortly after the report).
* Helping configuring and updating settings related to autolinking (e.g. https://github.com/python/peps/issues/2420#issuecomment-1100220723), webhooks (e.g. while setting up the Discord bot), apps (e.g. https://github.com/python/bedevere/issues/441), etc.
* Merge PRs when the CLA bot fails to recognize the email address of a user that signed the CLA, and therefore prevents the merging (see `edgedb/cla-bot#50`)

These tasks were performed either directly (for specific requests like adding already approved people to teams), or after discussions either on issues/PRs or on Discord (for uncontroversial things).  These also span a number of different repos, including `cpython`, `devguide`, `core-workflow`, `peps`, `bedevere`, `miss-islington`, `blurb_it`, `cherry_picker`.

I've also been working towards formalizing some of these processes (see. e.g. https://github.com/python/devguide/issues/886#issuecomment-1148609917 and https://github.com/python/core-workflow/pull/455) since the process is not too clear (see also https://github.com/python/core-workflow/issues/462) and some people have been pinging me directly for some of these tasks (which is fine with me).

I talked with @ewdurbin and they suggested me to bring this issue up to the SC.

[^1]:  it is not immediately obvious which tasks can be performed by org members, core devs, repo admins, and org admins

**Comment by brettcannon** [comment]
I've added this to our agenda.

**Comment by brettcannon** [comment]
We discussed this request, and due to the Python org having access to things greater than what is in scope of the SC, we think it's best to keep org access to a minimum.

**Comment by ezio-melotti** [comment]
Thanks for looking into this!
Is there a procedure for requesting privileged to specific repos?

**Comment by brettcannon** [comment]
It depends on the repo. For instance, `CPython` has https://devguide.python.org/devcycle/?highlight=brettcannon#current-administrators as guidelines for who should have access.
