### ISSUE TITLE
 Vote to promote Paul Ganssle as a core developer ended

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#13]
The vote closed 12 hours ago:

* Promote Paul Ganssle: 41 (95%)
* Don’t promote Paul Ganssle: 2 (5%)
* Total: 43 voters

Steering Committee: what's your call on this promotion?

https://discuss.python.org/t/vote-to-promote-paul-ganssle-as-a-core-developer/1826/8

cc @pablogsal

**Comment by brettcannon** [comment]
I've started the discussion. Assuming there's no objection I will email Paul asking for the appropriate details and then flip/request the right switches.

**Comment by pradyunsg** [comment]
A *very* gentle nudge on this -- anything left to do here?

**Comment by vstinner** [comment]
> A very gentle nudge on this -- anything left to do here?

No. I closed the issue.
