### ISSUE TITLE
[PEP 11] Promote wasm32-emscripten and wasm32-wasi platforms to tier 3

### ISSUE THREAD

**Issue by tiran** [python/steering-council#131]
I would like to request the promotion of the WebAssembly platforms wasm32-emscripten and wasm32-wasi to [PEP 11](https://peps.python.org/pep-0011/) tier 3.  wasm32-emscripten is Python in the browser / on NodeJS  used by [Pyodide](https://pyodide.org/), [PyScript](https://pyscript.net/), and Jupyter Lite. wasm32-wasi is WebAssembly System Interface, simply speaking WASM on the server inside a POSIX-like, capability-driven sandbox.

Both platforms fulfill PEP 11 requirements for tier 3

* @brettcannon and I will support the platforms
* We provide [stable buildbots](https://buildbot.python.org/all/#/builders?tags=%2Bwasm)

The platforms have some unique challenges. They provide only a limited, opinionated subset of POSIX APIs. Due to the nature of the runtime environments (browser, sandboxed WASI runtimes), parts of Python's stdlib are not available and will never be. Any API related to sockets, processes, threading, signals, and user accounts are not available, emulated, or restricted. You can find a longer list at https://github.com/python/cpython/tree/main/Tools/wasm .  We may want to include a caveat that these platforms impose restrictions on the stdlib.

In my opinion tier 3 for WASM is desirable to provide a foundation for Pyodide and future development. I expect that WebAssembly will become more important for both end-users and server-side/edge computing.

**Comment by encukou** [comment]
I've added it to the agenda.

**Comment by brettcannon** [comment]
Approved and recorded via https://github.com/python/peps/commit/b1ad37039fe391ce93df705c9ac469be23cd1e00 .
