### ISSUE TITLE
Request for deprecation exception for PyTracebackObject

### ISSUE THREAD

**Issue by kumaraditya303** [python/steering-council#136]
Hi,
 
 I have a [proposal](https://github.com/faster-cpython/ideas/discussions/407) to make tracebacks objects lazy and speed up CPython's exception handling. 
 This requires making fields of the `PyTracebackObject` lazily computed and allows other optimizations 
 like not materializing frame objects unless needed. I have a [PR](https://github.com/python/cpython/pull/95237) open which lazily computes the line numbers and this change alone provides 25% speedup (on a micro-benchmark), there would be more performance improvements as we implement the whole idea of lazy tracebacks.
 
 Unfortuntely, `PyTracebackObject` is exposed in public header file so these changes can be considered 
 backwards incompatible. There is **no documentation around `PyTracebackObject` in the docs** and the 
 header files contains no documentation around what the fields mean or represent.
 
 I propose to move the `PyTracebackObject` structure to the internal C API. I would like to make this an unstable API, but since PEP 689 was deferred, making it an internal API is the only option. It will exposed in the public C 
 API as an opaque struct. C API functions will be added to access the fields. This change will be properly 
 documented in the what's new entry and backwards shim will be provided in [pythoncapi-compat](https://github.com/python/pythoncapi-compat).
 It has been comfirmed that the lazily computing line number has [no impact on Cython](https://github.com/python/cpython/issues/95238#issuecomment-1223940601)
 and the lazy frame would require changing just two lines of code. I plan to make `tb_frame` and `tb_next` lazy apart from `tb_lineno`.
 
 Thanks for considering the proposal,
 
 Kumar Aditya
 
 Disourse discussion - https://discuss.python.org/t/leaky-abstractions-and-cpython-performance/18392/9
 
 CPython issue - https://github.com/python/cpython/issues/95238

**Comment by brettcannon** [comment]
> I have a [PR](https://github.com/python/cpython/pull/95237) open which lazily computes the line numbers and this change alone provides 25% speedup (on a micro-benchmark),

Would mind being specific about _what_ is sped up by 25%? Is it all of Python or just traceback objects? What about when you run this on the full benchmark suite for pyperformance?

**Comment by kumaraditya303** [comment]
> Would mind being specific about _what_ is sped up by 25%? Is it all of Python or just traceback objects? What about when you run this on the full benchmark suite for pyperformance?

The benchmark and results are posted on the [issue](https://github.com/python/cpython/issues/95238#issuecomment-1193908223).
I have tried it on PGO builds too and results are same on Linux with gcc.

**Comment by kumaraditya303** [comment]
FYI, I have posted another [benchmark](https://github.com/python/cpython/issues/95238#issuecomment-1229164762) using common pattern of `KeyError` and it sped up by 50% on Linux gcc PGO build.

**Comment by encukou** [comment]
Considering that the speedup is only measurable outside microbenchmarks, and the wide usage in third-party projects, the SC decided to not grant this exception. Please follow the deprecation process, with compiler deprecation warnings for at least 2 releases.

— Petr, on behalf of the SC

**Comment by kumaraditya303** [comment]
> Considering that the speedup is only measurable outside microbenchmarks,

What do you mean by this?

**Comment by encukou** [comment]
Sorry, I meant “in microbenchmarks”. Edited.
