### ISSUE TITLE
request: review basic approach of proposed Python 2 EOL page

### ISSUE THREAD

**Issue by brainwane** [python/steering-council#14]
Steering Council: please look at the work-in-progress draft of the Python 2.x EOL page I'm developing https://github.com/python/pythondotorg/issues/1500 .

Questions:
* I am designing this page to be very concise (currently under 660 words) and easy to read (currently has a Flesch Reading Ease score of 76/100 and Flesch-Kincaid Grade Level of 5.6, meaning a sixth-grader could read it). Is this basic approach okay with you?
  * Relatedly: In the initial display of this page, I'm going for broad accuracy over precision. For each generalization I can add a footnote with details and link to the specific claims, dates, citations, etc. Is that okay?
* Is it okay to name specific vendors who are offering post-EOL commercial support? If you'd like, instead of naming vendors in this page, I could quickly set up and link to a wiki page where they could list themselves. I think this will help users.
* Are there any major inaccuracies in what I have written?

I would appreciate a review by the end of the day Tuesday August 27th. Thank you.

**Comment by jackiekazil** [comment]
RE: 2. A wiki page listing vendors with a disclaimer that none of them are PSF-endorsed is probably best.

For all fairness, we should have something on that page that allows vendors who are not on the page to be added upon request. 

We should also list vendors alphabetically unless we want to assign weight via placement order.

**Comment by brainwane** [comment]
Thank you for your reviews and thoughts, everyone. I'm going to take those into account as I revise and post this (I hope) tomorrow on python.org (along with a new wiki page for vendors, with that disclaimer).

My in-progress project plan for communications is https://github.com/orgs/python/projects/1#card-26091749 -- I'll be putting that someplace easier to view soon, but here it is in rough form.

**Comment by brainwane** [comment]
Thanks all. It's up now at https://www.python.org/doc/sunset-python-2/ and I'll be asking for further reviews & advice in other issues.

**Comment by gvanrossum** [comment]
Tweeted: https://twitter.com/gvanrossum/status/1170949978036084736
