### ISSUE TITLE
PEP 683 -- Immortal Objects, Using a Fixed Refcount

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/steering-council#143]
Please consider PEP 683 -- "Immortal Objects, Using a Fixed Refcount".
https://peps.python.org/pep-0683/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was annonunced on the python-dev list (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

CC @eduardo-elizondo

**Comment by encukou** [comment]
Thanks! I added it to the agenda.

**Comment by encukou** [comment]
The Steering Council accepts PEP 683 (Immortal Objects) with reservations.

The main concern for the SC is ABI compatibility.
To mimimize possible risk, even to 32-bit Stable-ABI extensions, please implement the proposed “Solution for Accidental De-Immortalization” – that is, only immortalize objects whose deallocator will reset the refcount. (Note that this rules out automatically marking *all* objects immortal at the end of runtime init.)

Please update the PEP with performance measurements as the implementation is being finalized. We'll need to have another round of public disscussions about the performance impact once it's known.

*— Petr, on behalf of the SC*
