### ISSUE TITLE
Clarifications to PEP 646

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#145]
In https://github.com/python/cpython/pull/98267/files/805713c2b464bd66b0b1e8b438aba1feb7d3a64e#diff-04d29c98076c2d6bb75921ea9becb26a862544d39b71db87b6e354c759b9305d (hopefully that link works) it is noted that there was some vagueness in PEP 646 that is resolved by a series of tests that we're just now adding (actually we've been steadily increasing the test coverage during the 3.11 beta season).

I propose that we just clarify this behavior in the PEP itself rather than leaving the PEP a bit under-specified and relying on the test suite. Is the SC okay with this, in this particular case?

CC: @mrahtz

**Comment by encukou** [comment]
Without consulting the rest of the SC, I'll quote PEP 1:
> If changes based on implementation experience and user feedback are made to Standards track PEPs while in the Provisional or (with SC approval) Accepted state, they should be noted in the PEP, such that the PEP accurately describes the implementation at the point where it is marked Final.

My interpretation is that in general, it's expected that the initial implementation uncovers a few issues in the PEP. Changes should be reflected in the PEP *and* re-approved. I don't see why this particular case would be different.

(In the long term, of course, living specs shouldn't live in a standards-track PEP.)

**Comment by encukou** [comment]
The SC is okay with the changes.

— Petr, on behalf of the SC

**Comment by mrahtz** [comment]
Great news - thanks, Petr!
