### ISSUE TITLE
PEP 690 -- Lazy Imports

### ISSUE THREAD

**Issue by Kronuz** [python/steering-council#147]
Please consider PEP 690 -- Lazy Imports
https://peps.python.org/pep-0690/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was annonunced on the python-dev list (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [x] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [x] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

cc: @warsaw, @carljm

**Comment by encukou** [comment]
Thanks! I've added it to the SC agenda.

**Comment by gpshead** [comment]
Decision posted: https://discuss.python.org/t/pep-690-lazy-imports-again/19661/26
