### ISSUE TITLE
PEP 699 -- Remove private dict version field added in PEP 509

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/steering-council#153]
Please consider PEP 699 -- Remove private dict version field added in PEP 509
https://peps.python.org/pep-0699/

* [X] The PEP has been discussed in threads listed in its `Post-History` header
  
* [X] The PEP was annonunced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [X] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [X] The PEP includes endorsements from the projects/groups/people it helps
  Yes. Please check the discuss. We have input from a Cinder dev and Cython dev.
* [X] The PEP has a CODEOWNERS entry

**Comment by encukou** [comment]
Thanks! I added this to the agenda.

**Comment by Fidget-Spinner** [comment]
The PEP has been updated with SC suggestion to have a 2 cycle deprecation period. I would like to resubmit it for the new SC's consideration please.

**Comment by gpshead** [comment]
Thanks, back on our agenda (meeting after the holidays).

**Comment by Yhg1s** [comment]
We've accepted the PEP: https://discuss.python.org/t/pep-699-remove-private-dict-version-field-added-in-pep-509/19724/13
