### ISSUE TITLE
PEP xxx -- <PEP title here>

### ISSUE THREAD

**Issue by AAss123123123** [python/steering-council#154]
Please consider PEP xxx -- <PEP title here>
https://peps.python.org/pep-xxxx/

* [ ] The PEP has been discussed in threads listed in its `Post-History` header
  
* [ ] The PEP was annonunced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [ ] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [ ] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by hugovk** [comment]
Reported.
