### ISSUE TITLE
PEP 689 -- Unstable C API tier

### ISSUE THREAD

**Issue by encukou** [python/steering-council#155]
Please consider PEP 689 (Unstable C API tier) again.
https://peps.python.org/pep-689/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
* [x] The PEP was annonunced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP has a CODEOWNERS entry
  

Compared to the previous almost-accepted version, it adds a `PyUnstable_` prefix to all API in the new unstable tier. The underscore is reserved for private API.
Since functions will now need to be renamed when they’re moved from one stability tier to another, there’s more focus on not breaking pre-existing names until necessary (i.e. until an incompatible change is made).

(I'll add this to the agenda.)

**Comment by brettcannon** [comment]
As part of the proposal of APIs to change from [PEP 523](https://peps.python.org/pep-0523/), do you think `_PyEval_EvalFrameDefault()` should be listed as unstable?

**Comment by gvanrossum** [comment]
Yes.

**Comment by encukou** [comment]
Not as part of this PEP.

If this is API added to the unstable tier, it should have a test to verify that you can do something useful with it (without resorting to private API). I tried to write such a test, but failed. So I removed this from the PEP, and I won't be include this in the initial implementation.

Happy to help with adding the test & docs & moving to the new tier, but I'll need some example usage (and probably a bunch of tweaks or new API, too) from the experts. I'm leaving that for a later discussion.
