### ISSUE TITLE
Request PEP 387 exception to remove 4 functions broken since Python 3.11: Py_GenNew()

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#156]
Hi,

I tried to debug a reference leak in PyGen_New() but I failed to write an unit test to trigger the faulty code path: https://github.com/python/cpython/issues/99485 When I looked deeper, in fact PyAsyncGen_New(), PyCoro_New(), PyGen_New() and PyGen_NewWithQualName() functions are broken since Python 3.11. **It's no longer possible to call them.**

In Python 3.10, Python calls directly these functions. But in Python 3.11, a new internal function is called instead and the public functions were left unchanged. Problem: it's not possible to create a frame in a state which is accepted by PyGen_New().

I checked the PyPI top 5000 projects and no projects call these functions. I understand that **Python itself was the only consumer of these functions**.

**The way to create coroutines and generators changed in Python 3.11: they are now created with no frame but from a function instead.** The **old API** (create from a frame) is no longer usable, it **no longer makes sense**.

I propose to simply remove these functions in Python 3.12, and leave them broken (as they are, with the reference leak) in Python 3.11 (it's too late to remove these functions in a stable version). IMO it's better for developers to get a build error, rather than having to run the code and then see at runtime that these functions are badly broken.

@yhg1s told me that I need an exception for the backward compatibility (PEP 387), so I ask you: can I please get an exception and remove these 4 functions in Python 3.12?

* Issue: https://github.com/python/cpython/issues/99485
* PR to remove the 4 functions: https://github.com/python/cpython/pull/100075

**Comment by vstinner** [comment]
Other functions were removed without following PEP 387 process in the past, like PyFrame_BlockSetup() and PyFrame_BlockPop() removed in Python 3.11.

In Python 3.10, many functions related to parsers, symtable and AST got removed without following PEP 387, but these removals were a side effect of the approved PEP 617.

**Comment by sobolevn** [comment]
@vstinner what's the resolution? Were they removed? :)

**Comment by encukou** [comment]
The SC sees no reason to the skip deprecation period.
The functions can raise an exception if they cannot do their job, but please do follow the backwards compatibility policy (PEP 387).

Yes, we're aware that PEP 387 wasn't always followed in the past. That's bad. Don't treat it as a precedent. If PEP 387 is inadequate, we should change it rather than ignore it.

— Petr, on behalf of the SC
