### ISSUE TITLE
PEP 688 -- Making the buffer protocol accessible in Python

### ISSUE THREAD

**Issue by JelleZijlstra** [python/steering-council#158]
Please consider PEP 688 -- Making the buffer protocol accessible in Python
https://peps.python.org/pep-0688/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
    * I think it does, @gvanrossum could you help confirm?
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by gvanrossum** [comment]
> - [ ] typing-sig PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus: 
>        - I think it does, @gvanrossum could you help confirm?

I'm not sure I have the time to review all the threads (some seem very long, and it was a long time ago). I can review the PEP but that wouldn't really answer the question, would it?

**Comment by JelleZijlstra** [comment]
The PEP has now been extended with a section on backwards compatibility, as requested by the SC: python/peps#3007.
