### ISSUE TITLE
PEP 698 -- Override Decorator for Static Typing

### ISSUE THREAD

**Issue by stroxler** [python/steering-council#160]
Please consider PEP 698 (a method override decorator for static typing)
https://peps.python.org/pep-698/

* [x] The PEP has been discussed in threads listed in its Post-History header
* [x] The PEP was annonunced on [Discuss](https://discuss.python.org/t/pep-698-a-typing-override-decorator/20839) (link in Post-History)
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP has a CODEOWNERS entry
* [x] The PEP includes endorsements from the projects/groups/people it helps
  * Yes, in particular the discussion threads include remarks from the `overrides` runtime library author

**Comment by brettcannon** [comment]
> Type checkers already enforce compatibility rules for overrides

Is that by convention or is there a PEP that requires this? I would assume type checkers make sure that calling a subclass' method will be valid, but if you don't use `super()` in the subclass I don't see a requirement for the implicit override to type check to the superclass' method as the code flow won't reach the superclass otherwise. If I'm right, do you want to leave out requiring that overrides not violated the [Liskov Substitution Principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle)? I personally think the answer is "yes" and let type checkers decide if they want to offer a check that strict since there are times where a Liskov Substitution violation is what you want.

**Comment by JelleZijlstra** [comment]
To my surprise there is indeed no PEP that requires type checkers to check override compatibility. All major type checkers do provide this check because it's easy to introduce soundness problems if you don't check for it.

**Comment by stroxler** [comment]
I'm not sure we're talking about the same thing here, perhaps something needs to be reworded.

What type checkers already enforce is that the substitutions work at the type level. They don't particularly care whether `super()` is called, or about any semantic restrictions.

Specifically, as far as I am aware there is consensus that type checkers already should require already require subclass methods callable signatures to be a valid subtypes of the superclass method's signature.

Specifcally, this means that:

- all valid calls to the parent class method remain valid on the subclass
  - this requires parameter types to be subtypes
  - it also sets some other restrictions, e.g. that any additional arguments have default values
- the return type must of the subclass method must be a subtype of that of the parent class

If the parent method is untyped, then most of these rules become irrelevant since `Any` is considered both a valid subtype and supertype of every type; some of the rules that aren't type-based (e.g. new arguments must have default values) would still be enforced.

I'd be happy to reword this; the main point we were making is that this rule is already considered part of the type system, and PEP 698 is not proposing adding any additional consistency checks at all; in some of the early discussion threads folks misunderstood the PEP to be proposing new compatibility checks.

**Comment by stroxler** [comment]
I think this was under-specified in PEP 484, but as far as I know there is agreement across the typing community that this should be the case. Perhaps we should make a PEP for it?

The underlying rationale is that without this rule, subclassing would introduce arbitrary gaps in the type system. We do tolerate unsoundness in some cases, but subclassing is used heavily that without consistency checks static typing would probably become near-useless on nontrivial projects.

**Comment by stroxler** [comment]
On a close look, as far as I can see exactly one section of PEP 484 mentions method compatibility in subclassing, but only a bit indirectly in the context of saying that constructors should be compatible.

This is in [the section on the `Type[...]` construct](https://peps.python.org/pep-0484/#the-type-of-class-objects):

> There are some concerns with this feature: for example when new_user() calls user_class() this implies that all subclasses of User must support this in their constructor signature. However this is not unique to Type[]: class methods have similar concerns. A type checker ought to flag violations of such assumptions, but by default constructor calls that match the constructor signature in the indicated base class (User in the example above) should be allowed. A program containing a complex or extensible class hierarchy might also handle this by using a factory class method. A future revision of this PEP may introduce better ways of dealing with these concerns.

**Comment by gvanrossum** [comment]
IIUC the requirement for Liskov pretty much falls out of OO type checking -- we should always be allowed to safely upcast (e.g. from list to object) and this requires Liskov.

**Comment by brettcannon** [comment]
> Specifically, as far as I am aware there is consensus that type checkers already should require already require subclass methods callable signatures to be a valid subtypes of the superclass method's signature.



> the main point we were making is that this rule is already considered part of the type system



> I think this was under-specified in PEP 484, but as far as I know there is agreement across the typing community that this should be the case. Perhaps we should make a PEP for it?



> On a close look, as far as I can see exactly one section of PEP 484 mentions method compatibility in subclassing, but only a bit indirectly in the context of saying that constructors should be compatible.

From everything said above, it sounds like it's entirely convention right now that any type checking is done for the parameters of overridden methods (you could choose to interpret "ought" to mean "SHOULD" from a spec perspective, but that isn't necessarily clear). If this PEP wants to clarify this point and make it a requirement or at least a strong suggestion then I think that improves things by making it clear this isn't just about checking for method names.

**Comment by stroxler** [comment]
Yes, it does look like compatibility checks are just a convention at the moment.

I'd prefer not to tie the two topics in one PEP, they are related but not at all the same:
- This PEP is entirely about the `@override` decorator itself, which provides new semantics that only require checking the name
- Compatibility checks are a preexisting functionality that all type checkers provide (because they have to or they wouldn't be practical) but we have realized are not specified today.
- Compatibility rules are fairly technical and the edge cases have no relationship to @overrde rules, so I would much prefer not to specify them as an aside in PEP 698.

These topics are not just technically distinct, they catch different kinds of bugs:
- Compatibility checks are needed for basic soundness (which is why all type checkers enforce them, although we probably diverge in edge cases)
- The `@override` decorator is specifically useful for detecting bugs related to code *changes*, that compatibility rules alone cannot catch

**What to do about it?**

*For PEP 698*

It seems like the best path forward from the point of view of this one PEP would be to change the problematic sentence to

> This PEP does not specify rules for checking that overrides are compatible

which is more ambiguous, reflecting that the reality that this is unspecified.

*Making compatibility checks more than just a convention*

Separately, we probably should write a PEP specifying compatibility rules. Even though type checkers already enforce these, there may be disagreement on edge cases, and in addition future PEPs should probably be able to refer to this behavior, which is a problem right now (as illustrated by this PEP).

Does this plan sound reasonable?

If so, I can edit PEP 698 and also start a thread about compatibility rules on typing-sig.

If necessary we could withdraw PEP 698 until the new PEP has been written, so that PEP 698 can cross-reference it.

**Comment by gvanrossum** [comment]
I'm honestly very lukewarm about specifying compatibility checks. As you say, they are required for soundness. If anything, we could add a clarifying note to PEP 484 (as we've done in the past in cases where something was underspecified about which agreement existed). Also we should move this discussion to typing-sig rather than spamming the SC further.

**Comment by brettcannon** [comment]
> Does this plan sound reasonable?

That proposed PEP update sounds reasonable to me!

**Comment by stroxler** [comment]
That section of the PEP was reworded in https://github.com/python/peps/pull/2969

**Comment by brettcannon** [comment]
The SC discussed this PEP and is happy to accept this PEP!

@stroxler please send a PR to update the status of the PEP to accepted and we will let you handle sending PRs to implement it.
