### ISSUE TITLE
PEP 697 – Limited C API for Extending Opaque Types

### ISSUE THREAD

**Issue by encukou** [python/steering-council#161]
Please consider PEP 697 – Limited C API for Extending Opaque Types.
https://peps.python.org/pep-0697/

* [X] The PEP has been discussed in threads listed in its `Post-History` header.
* [X] The PEP was announced on [Discuss](https://discuss.python.org/t/19743)
* [X] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [X] The PEP includes endorsements from the projects/groups/people it helps (pybind11, HPy)
* [X] The PEP has a CODEOWNERS entry

**Comment by gpshead** [comment]
Accepted, pending some minor PEP text updates: https://discuss.python.org/t/pep-697-limited-c-api-for-extending-opaque-types/19743/28

**Comment by gpshead** [comment]
🎉
