### ISSUE TITLE
PEP 582 -- Python local packages directory

### ISSUE THREAD

**Issue by kushaldas** [python/steering-council#165]
Please consider PEP 582 -- Python local packages directory
https://peps.python.org/pep-0582/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
    Not exactly sure how to post links to random folks commenting how this helps them. The discussion thread has a few comments though.
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

As I see a lot of folks are at the same time against the idea of making things easier for new folks, instead they want one single tool to solve all problems of the Python ecosystem. This PEP is not trying to be that one single tool, instead taking care of the beginners is  the whole focus.

**Comment by kushaldas** [comment]
There are two possibilities on how to deal with `sysconfig` values related to the final path inside of the `__pypakcages__` directory. I have the one sounds better in the PEP itself, and also have an [issue](https://github.com/kushaldas/peps/issues/3) opened against my fork for the other option. I would love to hear what SC thinks about this part of the topic.

**Comment by brettcannon** [comment]
We will probably make a decision about the PEP overall before we worry about technical details about path calculation, so we will let you know in a broader response to the PEP.
