### ISSUE TITLE
PEP 701 -- Syntactic formalization of f-strings

### ISSUE THREAD

**Issue by pablogsal** [python/steering-council#166]
Please consider PEP 701 -- Syntactic formalization of f-strings
https://peps.python.org/pep-0701/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry

**Comment by pablogsal** [comment]
CC: @isidentical @lysnikolaou

**Comment by pablogsal** [comment]
@python/steering-council we have updated the PEP as required: https://github.com/python/peps/pull/3048

**Comment by Yhg1s** [comment]
The SC has accepted the PEP: https://discuss.python.org/t/pep-701-syntactic-formalization-of-f-strings/22046/119
