### ISSUE TITLE
PEP 684 -- A Per-Interpreter GIL

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/steering-council#167]
Please consider PEP 684 -- A Per-Interpreter GIL
https://peps.python.org/pep-0684/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] ~*typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:~
* [ ] ~*Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)~

The last round of discussion resulted in almost no changes to the PEP, which I'll take as an indication that the PEP is ready.  However, I'm open to further discussion if you have any lingering concerns.  (FWIW, my understanding is that there isn't much controversy with this proposal.)

Also, FYI, I'm still tracking the remaining work [here](https://github.com/ericsnowcurrently/multi-core-python/wiki/0-The-Plan).  That page is mostly up-to-date (and I'll be revisiting it in the next few days).  The remaining work is manageable for 3.12 and more so with others chipping in (which I anticipate is likely to happen).

**Comment by emilyemorehouse** [comment]
The SC has accepted this PEP! See our announcement on Discourse here: https://discuss.python.org/t/pep-684-a-per-interpreter-gil/19583/42
