### ISSUE TITLE
PEP 669 -- Low Impact Monitoring for CPython

### ISSUE THREAD

**Issue by markshannon** [python/steering-council#170]
Please consider PEP 669 -- Low Impact Monitoring for CPython for final approval.
https://peps.python.org/pep-0669/

PEP 669 was provisionally accepted late last year, on the condition that it worked and that its performance was acceptable.

It does work and its performance is acceptable, but there are some changes to the PEP so it will need to be considered.
To summarize the changes:
* The `MARKER` events have been removed. Monitoring individual code objects at line or instruction level provides the same (or more) capabilities.
* Events are now defined by plain `int`s, not enums, to allow monitoring before the `enum` module is loaded. Plain `int`s are faster as well.
* A `STOP_ITERATION` event has been added to handle the peculiar case of PEP 380 raising a `StopIteration` for a return.
* Events have been classified into those which can be disabled, those that cannot, and those derived from other events.

#### Implementation:

https://github.com/faster-cpython/cpython/tree/pep-669

#### Performance results:

I haven't really done any performance tuning yet, but performance is fine:
About 0.7% faster overall, and about 2% slower on coverage.

https://github.com/faster-cpython/benchmarking/tree/main/results/bm-20230223-3.12.0a5%2B-d579d2e

For a toy example using PEP 669 properly: https://gist.github.com/markshannon/da7588db3c883dc2006a727a10e00ca5
The overhead of PEP 669 is about 5% compared to the sys.settrace overhead of ~2000%

**Comment by gpshead** [comment]
Thanks for the updates! The steering council discussed this and agrees that it makes sense, proceed with your changes.
