### ISSUE TITLE
PEP 695 -- Type Parameter Syntax

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#173]
Please consider PEP 695 -- Type Parameter Syntax
https://peps.python.org/pep-0695/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  See https://discuss.python.org/t/pep-695-type-parameter-syntax/21646
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  (The typing SIG is generally in favor, does that count as an endorsement?)
* [x] The PEP has a CODEOWNERS entry (`@gvanrossum`)

SIG-specific:
* [x] *typing-sig* PEPs: Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus: Yes

CC: @erictraut

**Comment by emilyemorehouse** [comment]
The SC has accepted this PEP! See our announcement on Discourse here: https://discuss.python.org/t/pep-695-type-parameter-syntax/21646/92
