### ISSUE TITLE
PEP 707: A simplified signature for __exit__ and __aexit__

### ISSUE THREAD

**Issue by iritkatriel** [python/steering-council#178]
Please consider PEP 707 -- A simplified signature for ``__exit__`` and ``__aexit__``
https://peps.python.org/pep-0707/

[The discussion](https://discuss.python.org/t/pep-707-a-simplified-signature-for-exit-and-aexit/24402/1) and [the poll in it](https://discuss.python.org/t/pep-707-a-simplified-signature-for-exit-and-aexit/24402/32) show that there is almost unanimous consensus that we should do something about the exit signatures. However, it did not lead to a clear consensus on this PEP and there is [an alternative suggestion by Serhiy to redesign context managers from scratch](https://discuss.python.org/t/pep-707-a-simplified-signature-for-exit-and-aexit/24402/9?u=iritkatriel). Please consider that option as well.

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry

**Comment by brettcannon** [comment]
We discussed the PEP and have decided to reject it. Our thinking was the magic and risk of potential breakage didn't warrant the benefits. We are totally supportive, though, of exploring a potential context manager v2 API or `__leave__`.
