### ISSUE TITLE
PEP 709 -- Inlined comprehensions

### ISSUE THREAD

**Issue by carljm** [python/steering-council#179]
Please consider PEP 709 -- Inlined comprehensions
https://peps.python.org/pep-0709/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP has a CODEOWNERS entry

**Comment by carljm** [comment]
Note that I just merged a [one-sentence clarification to the PEP](https://github.com/python/peps/pull/3071/files), that async comprehensions are also inlined. This has always been the case in the implementation, but wasn't explicitly addressed in the PEP.

**Comment by Yhg1s** [comment]
The SC has discussed the PEP at length, and decided to accept it. As RM I would be grateful if you could submit it well before the 3.12 deadline (now May 22), preferably by next week :)

**Comment by carljm** [comment]
The implementation is ready and reviewed, so I think I will likely land it today!
