### ISSUE TITLE
PEP 659 -- Specializing Adaptive Interpreter

### ISSUE THREAD

**Issue by markshannon** [python/steering-council#180]
Please consider marking PEP 659 -- `Specializing Adaptive Interpreter` as accepted/final.
https://peps.python.org/pep-0659/

It is debatable whether this should have been a PEP in the first place, as It mainly documents internal details that we have implemented in 3.11 (with some parts in 3.10 and 3.12).

However, it is a PEP and rejecting or deferring it would make no sense now.

So, would the SC please:
1. Accept the PEP
2. Make recommendations for how to deal with similar documents that detail CPython enhancements in the future e.g. https://github.com/faster-cpython/ideas/issues/557

Thanks.

**Comment by brettcannon** [comment]
We talked this over and we would like you to please withdraw the PEP since, as you mentioned, it's debatable if it should have been a PEP to begin with.

We can talk about how to handle similar documents potentially at the language summit among other core devs.

**Comment by vstinner** [comment]
Hi. I showed https://peps.python.org/pep-0659/ to a friend and I was surprised to see it as a draft, since it's fully implemented in Python 3.11. Would it be possible to either mark as Final, or Withdraw it and explain why?

**Comment by vstinner** [comment]
See also https://github.com/python/peps/pull/3135#issuecomment-1532772983
