### ISSUE TITLE
[Enum] officially support `member.member` access and remove deprecation

### ISSUE THREAD

**Issue by ethanfurman** [python/steering-council#182]
Due to performance concerns, and seeing some good examples of when `member.member` access makes sense, I'd like to remove the deprecation and instead officially support it.

Does anything special need to happen to approve this, or do I just update the docs, code, etc.? The current PR [is here](https://github.com/python/cpython/pull/103236).

**Comment by gpshead** [comment]
additional context: this means closing https://github.com/python/cpython/issues/95077 as "not planned".

**Comment by gpshead** [comment]
A few of us chatted: agreed, keep the `member.member` behavior instead of the deprecation.

Focusing on some mix of existing exposed `enum` API compatibility and enabling better performance seems like a great idea.
