### ISSUE TITLE
PEP 702 -- Marking deprecations using the type system

### ISSUE THREAD

**Issue by JelleZijlstra** [python/steering-council#183]
Please consider PEP 702 -- Marking deprecations using the type system
https://peps.python.org/pep-0702/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [x] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus: I'm Jelle and I confirm this
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

I hope we'll still have time to include this in 3.12. The runtime implementation is fortunately simple, so if the PEP is accepted before the feature freeze it should be easy to get the implementation in.

**Comment by Yhg1s** [comment]
The SC is still discussing this PEP, but we have decided we can't pronounce on it in time for Python 3.12 (even with its new deadline of May 22), so we're deferring it until 3.12. (We're keeping it in our review queue, you don't have to resubmit it or anything.)

**Comment by JelleZijlstra** [comment]
The SC [indicated](https://discuss.python.org/t/pep-702-marking-deprecations-using-the-type-system/23036/32) that they were unhappy with having the new decorator in the `typing` module. I posted [an update](https://github.com/python/peps/pull/3442/files) to the PEP moving the new decorator to `warnings`. Please take another look.

**Comment by Yhg1s** [comment]
The SC has accepted the PEP: https://discuss.python.org/t/pep-702-marking-deprecations-using-the-type-system/23036/61
