### ISSUE TITLE
Two tweaks to PEP 669 (Low Impact Monitoring)

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#184]
See the [Discourse thread](https://discuss.python.org/t/pep-669-tweaks-proposal/25557) I started. These looks pretty uncontroversial, there are just a few hearts to my OP and one comment by Greg. With the SC's approval we'll update the PEP and implementation to match these tweaks.

**Comment by gpshead** [comment]
We chatted, the changes sound reasonable to us. Proceed.
