### ISSUE TITLE
A tweak in PEP 689 -- Unstable C API tier

### ISSUE THREAD

**Issue by encukou** [python/steering-council#185]
Hi,
When reviewing PEP 689 PR, we found a slightly better policy for moving an API from the unstable tier to the public tier. Instead of:

```diff
- The old name should remain available until the first incompatible change
- is made or the API is removed.
+ The old name should remain available until the API is deprecated or removed.
```

The policy of keeping old names means users don't need to make *unnecessary* changes when unstable API matures. But a deprecation means you'll need to stop using the API eventually.
And if anyone uses the unstable name, they've already signed up for removals without a deprecation period.

Is that OK?

The [published docs](https://devguide.python.org/developer-workflow/c-api/#moving-an-api-from-unstable-to-public) have the new text, I'll revert if you have objections.
For the PEP there's a [PR](https://github.com/python/peps/pull/3123/files?diff=unified&w=0#diff-111ebe4730400d1894dcedbbd9647de2ee646a0ca4f874f1bc00138f7066d0f8) with a [rendered preview](https://pep-previews--3123.org.readthedocs.build/pep-0689/).

**Comment by Yhg1s** [comment]
The SC is happy with the updated PEP.
