### ISSUE TITLE
PEP 695 -- Type Parameter Syntax: Proposed changes

### ISSUE THREAD

**Issue by JelleZijlstra** [python/steering-council#186]
While implementing PEP-695 I ran into a few issues that I think are best addressed by changing the PEP. The biggest change is to make type alias values and TypeVar bounds and constraints lazily evaluated, in line with the proposed semantics of PEP-649.

The proposed changes are here: https://github.com/python/peps/pull/3122/files.

My implementation in python/cpython#103763 already implements the proposed semantics.

Please take a look and let me know if you agree with these changes.

**Comment by JelleZijlstra** [comment]
I pushed another proposed change: https://github.com/python/peps/pull/3122/commits/f44696314e5a149a2a244ac08b89f2eca97de7d0. This comes out of the discussion in https://discuss.python.org/t/please-consider-delaying-or-even-rejecting-pep-695/26408 and specifies the scoping rules more concretely. I believe it is consistent with the scoping rules already present in the PEP, but more concrete and precise.

**Comment by Yhg1s** [comment]
The SC is happy with both of the proposed semantics changes, and the updated text.

**Comment by JelleZijlstra** [comment]
Thanks!
