### ISSUE TITLE
PEP 649 update

### ISSUE THREAD

**Issue by larryhastings** [python/steering-council#187]
We have some post-acceptance updates for 649, rolled up into one PR:

- Lots of clarification about intent--not changes, just better expressing the goal.
- Replace some unnecessary implementation details (that may change anyway) with descriptions of the desired outcome/behavior.
- Change the VALUE / FORWARDREF / STRING format constants to members of an IntEnum, which also means we can get rid of FORMAT_MIN and FORMAT_MAX.  A win all around.

My understanding is, such changes in an already-accepted PEP need SC signoff.  The PR is ready for your inspection.  Thanks!

**Comment by larryhastings** [comment]
https://github.com/python/peps/pull/3138

**Comment by Yhg1s** [comment]
The SC is happy with the changes.
