### ISSUE TITLE
PEP 709 follow-up

### ISSUE THREAD

**Issue by carljm** [python/steering-council#189]
Hello!

We need a steering council / 3.12 release manager ruling on how to handle a case where PEP 709 can change name resolution for a comprehension in a class scope, which was only identified after the PEP was accepted. See https://discuss.python.org/t/pep-709-one-behavior-change-that-was-missed-in-the-pep/26691/1 for a full discussion of the behavior change and an analysis of the real-world impact on several codebases I've tested (I wrote an AST scanning tool and have yet to find real-world code that would be impacted), as well as an outline of the possible paths forward for 3.12 and beyond.

Thanks, and sorry for not identifying this behavior change while writing the PEP!

**Comment by Yhg1s** [comment]
I've posted a longer update on the Discourse thread (https://discuss.python.org/t/pep-709-one-behavior-change-that-was-missed-in-the-pep/26691/21), but in short the SC decided the newly uncovered semantics change is too problematic, and we have to unaccept the PEP and roll back the implementation change. (Sorry.)
