### ISSUE TITLE
Any core developer interested in doing a video interview for the Moscow Python Conference?

### ISSUE THREAD

**Issue by ejodlowska** [python/steering-council#19]
The Moscow Python Conference 2020 conference is hoping to air some recorded interviews of prominent Pythonistas at their annual conference (happening March 27). If anyone is interested in being interviewed, let me know! Here are the questions they have prepared!

- What is your favorite Python feature introduced within the last few years?
- What is the main challenge for async Python programming?
- What one feature from any other programming language is a good fit for Python?
- What are the strongest and weakest points in the Python ecosystem nowadays?
- What parts of Python do you like to work on in the near future?

**Comment by brettcannon** [comment]
Closing this as we are well past the deadline.
