### ISSUE TITLE
PEP 713 -- Callable Modules

### ISSUE THREAD

**Issue by amyreese** [python/steering-council#191]
Please consider PEP 713 -- Callable Modules
https://peps.python.org/pep-0713/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry

**Comment by gpshead** [comment]
Hi, thanks for writing up the nice PEP spawning the lively discussion around callable modules.

The steering council has discussed this PEP and decided to Reject it.  (as I mentioned we were leaning towards in https://discuss.python.org/t/pep-713-callable-modules/26127/66?u=gpshead)

We didn't feel that there was a compelling reason to have it even though it clearly could be done from a consistency point of view.  I wouldn't be surprised if this idea comes up again in the future.  If so, this is a useful prior discussion to refer to for when it does.

- The Python Steering Council

**Comment by AA-Turner** [comment]
Please may this rejection notice be posted to Discourse? (Both to update the PEP, and for a wider audience.) The Discussions-To thread is currently locked.

A
