### ISSUE TITLE
Backwards Compatibility Policy updates/clarifications

### ISSUE THREAD

**Issue by encukou** [python/steering-council#196]
(Dropped the ball on this for a few months, but...)
Please consider some changes to our backwards compatibility policy.

Discussion: https://discuss.python.org/t/22042
PR: https://github.com/python/peps/pull/2931

These are mostly clarifications and/or codifying the status quo, but, you might disagree, but one change is somewhat controversial: explicitly noting that *if something is not documented at all, it is *not* automatically considered private.*

**Comment by gpshead** [comment]
replied on the thread, we're happy with the changes.
