### ISSUE TITLE
PEP xxx -- <PEP title here>

### ISSUE THREAD

**Issue by Deahdog** [python/steering-council#197]
Please consider PEP xxx -- <PEP title here>
https://peps.python.org/pep-xxxx/

* [ ] The PEP has been discussed in threads listed in its `Post-History` header
  
* [ ] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [ ] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [ ] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

My proposal you stay the hell away from my existance you and all you people I am the father I'm joining the eye your just some thing that threw away his soul and climbed in his skin you traitor mom killer my mom my real brother survived been looking out for me in heaven your not him don't ever touch me again me and Satan gonna have a lot going on in existance none of you are family disconnect from meeeeee disable little brother project die horrible I hate you

**Comment by hugovk** [comment]
Reported to GitHub for abuse.
