### ISSUE TITLE
Fix name mention in 2019-02-26 Steering Council Update

### ISSUE THREAD

**Issue by cjerdonek** [python/steering-council#2]
[This line](https://github.com/python/steering-council/blame/c672326c30bf4ed42a4909c05df4daabddd8b5f8/updates/2019-02-26_steering-council-update.md#L44) of the Feb. 26 update says:

> Consider PEP 580 - Chris Jerdonek request (PENDING)

I believe this is supposed to say Jeroen Demeyer (not me).

**Comment by cjerdonek** [comment]
Thanks!

**Comment by willingc** [comment]
Thanks @cjerdonek. I think that I had pulled the name from a message and not the PEP. I appreciate that you caught the error. 👍

**Comment by cjerdonek** [comment]
No problem, @willingc, and thank you. I'm guessing it also had something to do with the fact that our names both start with "Jer" (like an auto-completion type error).
