### ISSUE TITLE
Time zone module: PEP or no PEP?

### ISSUE THREAD

**Issue by pganssle** [python/steering-council#20]
Greetings Steering Council,

Last year at the language summit, I proposed adding [time zones to the standard library](https://pyfound.blogspot.com/2019/05/paul-ganssle-time-zones-in-standard.html), and it seems that it was a *mostly* uncontroversial proposal. It has taken me a while to actually get things together, but I am almost at the stage that I will need some review for the public interface. I am hoping to get at least a pure Python version of this in before the feature freeze this year.

At last year's language summit, I suggested that I should write a PEP, mainly based on the fact that a PEP had already been proposed on this topic, [PEP 431](https://www.python.org/dev/peps/pep-0431/), and been rejected. However, reading through PEP 431 and [PEP 495](https://www.python.org/dev/peps/pep-0495/), I realized that both of these are really looking to make changes to the `datetime` type, whereas (now that PEP 495 is available), my new proposed module is self-contained and needs to make no changes to existing interfaces, so I am not sure if this needs a PEP or if I should just go through normal channels for review.

I can see a few possible reasons to go with a PEP:

1. To document the interface of the new module (though this can and *will* be covered in the Python documentation anyway).
2. I am proposing that the implementation would default to using the system time zones, and I plan to propose a few mechanisms for the search path:
    - One or possibly a few runtime environment variables (e.g. `PYTHON_TZPATH`) that would affect where the module looks for time zones.
    - A compile-time option specifying the default search path (to allow distros that know the path ahead of time to prune out the unnecessary options, or add missing options)
    - A function in the module to modify it from Python
  Seems like several of those options might trigger a PEP.
3. I intend to add an opportunistic dependency on a PyPI-manage package, `tzdata` (which is to say that if you have `tzdata` installed and your system is missing a given time zone or has no time zones installed, it will load from the package).

The main downside of writing a PEP that I see (beyond the obvious "SC time is valuable and I shouldn't hijack it to get a code review") would be that PEPs are frozen after acceptance and eventually the "documentation by PEP" may grow stagnant.

Please let me know how you'd like me to proceed.

**Comment by pganssle** [comment]
I decided to go ahead and start working on the PEP and I've become increasingly convinced that it will be useful, so I'm going to close this issue and just move ahead with the PEP.

Thanks, sorry for the noise!

**Comment by vstinner** [comment]
Even if the proposed change is not controversial, a PEP is helpful as an overall design document. In my experience, it helped me in the past to write down the design in a PEP, rather than wasting too much time on refactoring too frequently the implementation.
