### ISSUE TITLE
Archive the typed-ast repository

### ISSUE THREAD

**Issue by hauntsaninja** [python/steering-council#200]
I've been maintaining https://github.com/python/typed_ast. We announced the death of the project about two years ago: https://github.com/python/typed_ast/issues/179. The functionality this library aimed to provide got mostly subsumed into the standard library in Python 3.8 and we've transitioned all of its biggest users away from the project. And of course, the code on PyPI continues to be functional for any current users on current Python versions (including 3.12 beta).

In https://discuss.python.org/t/new-python-organization-repository-policy/17376 , the Steering Council reaffirmed its purview over the birth of repositories in the Python org, so I'm assuming you're also interested in the death of repositories :-) I also don't have the ability to archive the repo and I'm not exactly sure who does.

**Comment by gpshead** [comment]
Its EOL has been announced and it'll remain up on PyPI, I suggest @ambv just go ahead and archive the project on Github (I believe @ambv has permissions to do that?).  No need to wait for the SC as I believe [it is equally easy to unarchive](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories) if further maintenance were ever desired. It is also easy to fork an archived repo into a non /python/ org for further maintenance AFAIK.

**Comment by hugovk** [comment]
Before archiving, I suggest editing the README to put a prominent notice that it's EOL.

(You could optionally release it to PyPI so it shows there too, and if so, could use the [`Development Status :: 7 - Inactive`](https://pypi.org/search/?c=Development+Status+%3A%3A+7+-+Inactive) Trove classifier.)

**Comment by gpshead** [comment]
Yep, _(steering council chatted today:)_ we're fine with this. Please do a final PyPI release update with the docs saying it is EOL and unmaintained, including the trove classifier so that it is clear to people seeing [the package on PyPI](https://pypi.org/project/typed-ast/) clearly see that it won't be updated further.  Then feel free to archive the Github repo.

**Comment by hauntsaninja** [comment]
Thank you! I've added a notice to the README, the long description, added the classifier and made the final release. I'll wait a few days just in case and then ask Łukasz to archive the repo.

**Comment by ambv** [comment]
As it's easy to un-archive if needed, I already did that.
