### ISSUE TITLE
Request for comment: datetime.h and PEP-387

### ISSUE THREAD

**Issue by erlend-aasland** [python/steering-council#208]
The `_datetime` extension module exposes a capsulated C API via the datetime.h header. That header is not exposed though Python.h; it must be explicitly included.

Does the datetime.h header fall under the PEP-387 umbrella? For example, do we need to heed PEP-387 in order to change the capsulated `_datetime` C API?

cc. @pganssle

**Comment by Yhg1s** [comment]
Yes, the SC thinks PEP 387 applies.

**Comment by erlend-aasland** [comment]
Thanks!
