### ISSUE TITLE
Please formally reject PEP-536

### ISSUE THREAD

**Issue by ericvsmith** [python/steering-council#209]
This PEP suggested moving f-strings to the python grammar. It's basically what was implemented by PEP 701 – "Syntactic formalization of f-strings". As such, 536 is obsolete.

I was going to mark 536 as rejected, but I think there should be formal SC action to reject it, not some random committer rejecting it.

I'll do the actual work of updating the PEP, unless you want to.

Thanks.

**Comment by merwok** [comment]
Alternatively, the author @flying-sheep could withdraw it.

**Comment by flying-sheep** [comment]
How do I do that?

**Comment by merwok** [comment]
With a PR!
Not much info in the meta-PEP: https://peps.python.org/pep-0001/#pep-review-resolution

**Comment by flying-sheep** [comment]
I can just link here I guess. I agree with @ericvsmith that 701 does exactly what I intended to change with 536 (only a few years later).

**Comment by merwok** [comment]
I do believe it should be a link to a mailing list post (nowadays discuss).

**Comment by flying-sheep** [comment]
Ugh, yeah it does need to be that.
