### ISSUE TITLE
Submission for SC consideration: PEP 585 "Type Hinting Generics In Standard Collections"

### ISSUE THREAD

**Issue by ambv** [python/steering-council#21]
I'd like to ask the Steering Council for a decision whether this PEP should be accepted and implemented for Python 3.9.

I wrote this PEP last year and since then it got through several significant editing rounds. We have also done several discussion rounds, and there's a prototype implementation by @gvanrossum  and @ethanhs.

### PEP text
- https://www.python.org/dev/peps/pep-0585/

### typing-sig discussion
- https://mail.python.org/archives/list/typing-sig@python.org/thread/5YDRDAN273O2L5YAPYK3DGN7EREH5N6Y/#2XZM7RWU3MFFAXAPAKZ6TDNIH732FWUV
- https://mail.python.org/archives/list/typing-sig@python.org/thread/A6G6OG3GV2D6HAMHAYG7HDRSWHOOHAT6/#LXTC7KHMS2J4VRLD3HN7EJZQHEBUBS5J
- https://mail.python.org/archives/list/typing-sig@python.org/thread/75TYWHHCLJ4CLWFLVME3EJHVLEYXFUGX/#75TYWHHCLJ4CLWFLVME3EJHVLEYXFUGX

### python-dev discussion
- https://mail.python.org/archives/list/python-dev@python.org/thread/VYUM3GLXCDFKU6URHN5IPT2UTVESEO4B/#VYUM3GLXCDFKU6URHN5IPT2UTVESEO4B

### prototype implementation
- https://github.com/python/cpython/pull/18239; based on
- https://github.com/gvanrossum/cpython/tree/pep585

**Comment by vstinner** [comment]
The Steering Council approved the PEP, congrats ;-)
https://mail.python.org/archives/list/python-dev@python.org/thread/HW2NFOEMCVCTAFLBLC3V7MLM6ZNMKP42/
