### ISSUE TITLE
PEP 731 -- C API Working Group Charter

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#210]
Please consider PEP 731 -- C API Working Group Charter
https://peps.python.org/pep-0731/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [ ] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections) (It doesn't quite -- but this is a process PEP)
* [ ] The PEP includes endorsements from the projects/groups/people it helps (again, I'm not sure this is needed for a process PEP)
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by vstinner** [comment]
Is there an update on this issue open for 3 weeks?

@encukou asked multiple times to wait for the C API Working Group before making some C API changes, but this working group doesn't exist yet.

**Comment by Yhg1s** [comment]
There is no update yet, no. Yes, please wait for the C API WG to be decided on. There's no rush on any of the changes you want to make, given that we have 6 more alpha releases and nearly half a year before the beta. Please be conservative with your changes.

**Comment by emilyemorehouse** [comment]
On behalf of the SC, we're pleased to accept this PEP with one requested change. 🙂 Since PEPs serve as historical documents, we would like the initial working group members to be listed explicitly in the PEP instead of relying on the author list. Additionally, we approve the initial membership list per the current authors.

**Comment by hugovk** [comment]
@python/organization-owners Please block @pathum2583-eng, they've spammed before (https://github.com/python/peps/pull/4925, https://github.com/hugovk/top-pypi-packages/pull/60).
