### ISSUE TITLE
Is it OK to remove _PyObject_Vectorcall?

### ISSUE THREAD

**Issue by encukou** [python/steering-council#212]
PEP-590 says:

> The underscore in the names `_PyObject_Vectorcall` and `_Py_TPFLAGS_HAVE_VECTORCALL` indicates that this API may change in minor Python versions. When finalized (which is planned for Python 3.9), they will be renamed to `PyObject_Vectorcall` and `Py_TPFLAGS_HAVE_VECTORCALL`. The old underscore-prefixed names will remain available as aliases.

I'm not aware of a decision to override the PEP. But the reasoning behind the changes is scattered in a maze of issues, PRs and topics that were never collected into a PEP, so it's very possible that I'm missing something. (It seems @vstinner is in charge of the removals, but I don't know where to ask or discuss -- see e.g. [here](https://github.com/python/cpython/issues/106084#issuecomment-1646575040)).

The question I want to ask is practically intractable at this point, so I'll ask a simple one instead: 
Does the SC think that it is OK to remove `_PyObject_Vectorcall` without a change to PEP-590, new PEP, or SC decision?

**Comment by vstinner** [comment]
When I removed these private functions, I wasn't aware that PEP 590 had a specific section about them.

Last June, I only found 8 projects using it: https://github.com/python/cpython/issues/106084#issuecomment-1614440847

In the meanwhile, I added some vectorcall APIs for Python 3.8 in the pythoncapi-compat project: https://pythoncapi-compat.readthedocs.io/en/latest/api.html#c.PyObject_Vectorcall

**Comment by gpshead** [comment]
I captured my personal thoughts on this theme in https://github.com/python/cpython/issues/111481#issuecomment-1794211126

**Comment by gpshead** [comment]
The SC has been chatting about the overall theme behind recent presumed-private C API removals and we're happy to see that the C API working group appears to be looking into the question per Guido on [106320](https://github.com/python/cpython/issues/106320#issuecomment-1794240140).

**Comment by gvanrossum** [comment]
Of course that would require there to *be* a C API WG, which is awaiting approval of PEP 731 (https://github.com/python/steering-council/issues/210).

**Comment by encukou** [comment]
Right. There are strong personal opinions floating around, spanning the full range of "revert it all"–"moratorium"–"full steam ahead".

**Comment by brettcannon** [comment]
> Of course that would require there to _be_ a C API WG, which is awaiting approval of PEP 731 (#210).

Correct, hence why it's actively being discussed by the SC.

**Comment by vstinner** [comment]
Update: PEP 590 aliases kept for backward compatibility were restored in Python 3.13 by https://github.com/python/cpython/pull/112115

**Comment by Yhg1s** [comment]
Now that the C API WG PEP is accepted and this has been solved for 3.13 anyway, the SC is leaving this question for the WG.
