### ISSUE TITLE
PEP 729 -- Typing governance process

### ISSUE THREAD

**Issue by JelleZijlstra** [python/steering-council#213]
Please consider PEP 729 -- Typing governance process
https://peps.python.org/pep-0729/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [x] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus: Jelle here. For the most part, the PEP generated surprisingly little discussion. The main point of contention was around how the spec should work; this is discussed in "Rejected ideas". 
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by emilyemorehouse** [comment]
On behalf of the SC, we're pleased to accept this PEP. 🙂
