### ISSUE TITLE
PEP 730 -- Adding iOS as a supported platform

### ISSUE THREAD

**Issue by freakboy3742** [python/steering-council#218]
Please consider PEP 730 -- Adding iOS as a supported platform
https://peps.python.org/pep-0730/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
   Feedback from the following individuals has been incorporated:
   * @ronaldoussoren, the maintainer of much Apple/macOS ecosystem tooling
   * @misl6, a member of the @kivy core team involved in iOS support
   * @mhsmith, member of the @BeeWare core team, and maintainer of @chaquo
   * @holzschu, maintainer of [a-shell](http://github.com/holzschu/a-shell), an iOS terminal/shell environment with built-in Python support; and [Carnets-Jupyter](https://github.com/holzschu/carnets/), an iOS Jupyter environment.
   * @alexstaravoitau, maintainer of [Juno](https://juno.sh) (an iOS Jupyter environment) and [TinkerStellar](https://tinkerstellar.com) (an iOS environment providing interactive Python tutorials)

* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by emilyemorehouse** [comment]
Thanks for the very thorough and well-written PEP! The SC is happy to accept it.

We aren't worried about the lack of x86_64 hardware (though perhaps this will be a push to get some old hardware donated) nor the deprecation warning for the `--undefined dynamic_lookup` flag – these are technical details that we can find solutions to in the future as needed.

**Comment by jakirkham** [comment]
The PEP still shows as ["Draft" under "Status"]( https://github.com/python/peps/blame/77a9780295d9876515f8c5d9bccee4668aa8c8de/peps/pep-0730.rst#L6 ). Is that expected? Or does this need an update?

**Comment by JelleZijlstra** [comment]
Probably an oversight, posted python/peps#3694 to update the status.
