### ISSUE TITLE
PEP 732 -- The Python Documentation Editorial Board

### ISSUE THREAD

**Issue by jablonskidev** [python/steering-council#220]
Please consider PEP 732 -- The Python Documentation Editorial Board
https://peps.python.org/pep-0732/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [ ] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to Guido/Jelle's confirmation that the PEP captures typing-sig discussions/consensus:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by Yhg1s** [comment]
PEP accepted! https://discuss.python.org/t/pep-732-the-python-documentation-editorial-board/36710/9
