### ISSUE TITLE
PEP 737 -- Unify type name formatting

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#227]
Please consider PEP 737 -- Unify type name formatting
https://peps.python.org/pep-0737/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *typing-sig* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by vstinner** [comment]
> The PEP includes endorsements from the projects/groups/people it helps

Would you mind to elaborate what it means? The PEP should address all requests that other people sent so far.

**Comment by vstinner** [comment]
Hi, what's the status of this PEP? Do you need me to provide more information?

**Comment by Yhg1s** [comment]
The status is that you've submitted it to the SC, and now the SC has it on the agenda and will respond when it's discussed the PEP.

**Comment by Yhg1s** [comment]
The SC accepts the updated PEP.
