### ISSUE TITLE
PEP 705 -- TypedDict: Read-only items

### ISSUE THREAD

**Issue by JelleZijlstra** [python/steering-council#229]
Please consider PEP 705 -- TypedDict: Read-only items
https://peps.python.org/pep-0705/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [x] *typing-sig* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP: https://github.com/python/typing-council/issues/14#issuecomment-1928621660
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

(Posting this here instead of @alicederyn to remove a step of bureaucracy. I just posted the Typing Council's recommendation to accept the PEP.)

**Comment by Yhg1s** [comment]
The Steering Council has decided to follow the Typing Council's recommendation (quoted verbatim below) and accepts PEP 705.

For the record, the Typing Council said:

> The Python Typing Council recommends accepting PEP 705, “TypedDict: Read-only items”. The PEP's motivation and rationale are well written and clearly describe how attribute mutability can hurt ergonomics in common use cases. Variants of the idea have been discussed and iterated on over the last year and a half, and reflect learnings from previous community experience with TypedDict features — for instance, the final version incorporates lessons from PEP 655. We expect PEP 705 to compose well with existing TypedDict features. The type qualifier introduced would likely work well if we extended support to Protocols in the future. The PEP has already been implemented in one type checker and we foresee no major issues in getting it implemented in other type checkers.
