### ISSUE TITLE
PEP 738 -- Adding Android as a supported platform

### ISSUE THREAD

**Issue by mhsmith** [python/steering-council#231]
Please consider PEP 738 -- Adding Android as a supported platform
https://peps.python.org/pep-0738/

This follows the same approach as PEP 730, adding iOS support, which has already been accepted.

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
  * @freakboy3742, leader of @beeware ([Discuss post](https://discuss.python.org/t/pep-738-adding-android-as-a-supported-platform/40975/6))
  * @misl6, core developer of @kivy ([Discuss post](https://discuss.python.org/t/pep-738-adding-android-as-a-supported-platform/40975/9))
* [x] The PEP has a CODEOWNERS entry

**Comment by mhsmith** [comment]
As requested, I've clarified the availability of buildbots and GitHub Actions resources for testing Python on Android:

* https://github.com/python/peps/pull/3700

**Comment by Yhg1s** [comment]
The SC accepts PEP 738. Just to clarify, though: like with iOS, the buildbot will be a requirement for the platform be considered tier 3 (and listed that way in PEP 11), but in the mean time changes can go in to support the platform.
