### ISSUE TITLE
PEP 734 -- Multiple Interpreters in the Stdlib

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/steering-council#234]
Please consider PEP 734 -- Multiple Interpreters in the Stdlib
https://peps.python.org/pep-0734/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

This is basically a cleaner version of PEP 554, so this has been a long time coming.  I'm hoping we can get this in for 3.13.  I'd be glad to discuss this with you (office hours?) if you have any concerns.  Just let me know.  Thanks!

**Comment by ericsnowcurrently** [comment]
FYI, I had forgotten to merge my recent changes to the PEP.  I just merged the PR.

**Comment by ericsnowcurrently** [comment]
What sort of ETA should I expect for a decision on this?

**Comment by Yhg1s** [comment]
A couple of weeks, at least. Maybe more before the actual decision but we'll probably have back-and-forth at that point. It's on the agenda to discuss next week, but it's not a simple PEP.

**Comment by warsaw** [comment]
The SC has [decided to Defer](https://discuss.python.org/t/pep-734-multiple-interpreters-in-the-stdlib/41147/24) this PEP.
