### ISSUE TITLE
PEP 741 -- Python Configuration C API

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#237]
Please consider PEP 741 -- Python Configuration C API
https://peps.python.org/pep-0741/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *Typing* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by gvanrossum** [comment]
Whoa. I do *not* think there is sufficient agreement on this in the discussion.

**Comment by zooba** [comment]
I agree. I have opposed the fundamental premise of this PEP in the discussion, and it's not been addressed in the discussion or changed at all.

I do not believe the SC should be considering this PEP at this time.

**Comment by vstinner** [comment]
> Whoa. I do not think there is sufficient agreement on this in the discussion.

I did my best to record all opinions in the Rejected Ideas. The PEP is already quite long, so I didn't record everything.

Right, there are disagreements, and that's why I'm asking the Steering Council for advice on how to move on on this PEP.

**Comment by vstinner** [comment]
If this PEP is accepted, I plan to attempt to write a backport for Python 3.8-3.12 in my experimental [deadparrot project](https://github.com/vstinner/deadparrot): shared library providing a compatibility layer between old/new C APIs and old/new Python versions.

**Comment by vstinner** [comment]
Closed in favor of the new submission: https://github.com/python/steering-council/issues/246.
