### ISSUE TITLE
PEP 742 -- Narrowing types with TypeIs

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#238]
Please consider PEP 742 -- Narrowing types with TypeIs
https://peps.python.org/pep-0742/

(As you may remember, [PEP 724](https://peps.python.org/pep-0724/) proposed to change the existing `TypeGuard` special form (introduced by [PEP 647](https://peps.python.org/pep-0647/)) to implement more desirable semantics for type guards, creating some edge cases where the semantics would change for existing code (causing type checkers to occasionally produce new errors). There was all round agreement that the new semantics are in most cases better, but a majority of the TC found the backward incompatibility in edge cases unacceptable. Therefore Jelle drafted PEP 742, which proposes a new name for the new semantics (without proposing to deprecate `TypeGuard`, as its different semantics are occasionally useful). There was considerable bikeshedding on the name of the new special form, but we ultimately landed and agreed on `TypeIs`. Details of the breaking edge cases are in PEP 724’s [Backwards Compatibility](https://peps.python.org/pep-0724/#backwards-compatibility) section.)

* [x] The PEP has been discussed in threads listed in its `Post-History` header
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
* [x] The PEP has a CODEOWNERS entry

SIG-specific:
* [x] *Typing* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP: https://discuss.python.org/t/pep-742-narrowing-types-with-typeis/45613/34
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by emilyemorehouse** [comment]
The Steering Council has decided to follow the Typing Council's recommendation and accepts PEP 742. 🎉
