### ISSUE TITLE
Please consider PEP 667 -- Consistent views of namespaces

### ISSUE THREAD

**Issue by markshannon** [python/steering-council#239]
Please consider PEP PEP 667 -- Consistent views of namespaces
https://peps.python.org/pep-0667/

* [ ] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
   https://discuss.python.org/t/pep-667-consistent-views-of-namespaces/46631
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [ ] The PEP includes endorsements from the projects/groups/people it helps
     It helps us (the Faster CPython team), does that count? 🙂 
* [x] The PEP has a CODEOWNERS entry

**Comment by gpshead** [comment]
Acceptance message posted with one edit needed while marking it accepted: See https://discuss.python.org/t/pep-667-consistent-views-of-namespaces/46631/25

Thanks!
