### ISSUE TITLE
PEP 617: New PEG parser for CPython -- please review ASAP

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#24]
I, @pablogsal and @lysnikolaou have been working on a new parser for CPython based on PEG technology. We are presenting our work at the online language summit (Wd 4/15, 9:45am Pacific time) and we are hoping to land the code in time to make it to 3.9.0 alpha 6, which is planned to go out on Wednesday, April 22, i.e. in 9 days. Please read [PEP 617](https://www.python.org/dev/peps/pep-0617/) for more details.

We are currently down in the engineering work of getting the last few details matching between the old and the new parser (e.g. certain error messages representing edge cases), and I am certain that we will be able to merge the code in time for alpha 6, provided we have SC approval (or at least non-opposition) and provided the general response at the online language summit is positive enough. (And we get review from a core dev other than the PEP authors.)

**Comment by warsaw** [comment]
I've added this to the SC agenda for 2020-04-20.

**Comment by brettcannon** [comment]
Just some quick points after reading the PEP:
- https://www.python.org/dev/peps/pep-0617/#syntax has the meta grammar _before_ all of the syntax is explained which is a little jarring since there is way more than just the rule naming; maybe move it to after the full discussion of the operators?
- "In the specific case of the new proposed PEG grammar for the Python"; is that an extra "the" at the end?
- I assume the proposed flag for flipping between the parsers is a `-X` flag?

**Comment by gvanrossum** [comment]
> 
> - https://www.python.org/dev/peps/pep-0617/#syntax has the meta grammar before all of the syntax is explained which is a little jarring since there is way more than just the rule naming; maybe move it to after the full discussion of the operators?

Good point, we'll try to do something about it.

> - "In the specific case of the new proposed PEG grammar for the Python"; is that an extra "the" at the end?

Oops. :-)

> - I assume the proposed flag for flipping between the parsers is a -X flag?

Actually we have added a new flag `-p {old|new}`. Is that overkill?

**Comment by brettcannon** [comment]
> Actually we have added a new flag -p {old|new}. Is that overkill?

We will discuss on the SC, but my personal answer is "yes" for a flag that will only last one release (and honestly I don't think it's even needed; you did such a thorough job testing that anything that fails is going to be a bug that needs fixing anyway, so being able to flip to the old parser just postpones having to wait one bugfix release).

**Comment by warsaw** [comment]
I also support a flag, but if it's only going to be around for a single release, I think an `-X` flag is easier to remove.

**Comment by gvanrossum** [comment]
First two points [fixed](https://github.com/python/peps/pull/1372) in PEP. Last point [addressed](https://github.com/we-like-parsers/cpython/pull/92) in the code.

**Comment by brettcannon** [comment]
https://mail.python.org/archives/list/python-dev@python.org/thread/FTXPZTEHX25QXEMY2QJP3M6KZVXEQNHK/ is the announcement of the acceptance of the PEP!

**Comment by gvanrossum** [comment]
Thanks for the support! Now we'll scramble to get something ready for alpha 6.
