### ISSUE TITLE
Update standing delegations doc for Typing Council

### ISSUE THREAD

**Issue by ncoghlan** [python/steering-council#241]
Reviewing https://github.com/python/steering-council/blob/main/process/standing-delegations.md it occurred to me that it should probably reference some of the other governance delegation PEPs accepted since it was last updated: https://peps.python.org/topic/governance/

(At least the Typing Council seems worth mentioning, as well as referencing PEP 609 for the way that PyPA makes use of the packaging related standard delegations. The Documentation Editorial Board is less clearcut, since the standard delegation doc was originally specifically about PEPs, but it still feels like a plausible inclusion)

I'd be happy to put a PR together if the SC agrees it makes sense to add these references.

**Comment by JelleZijlstra** [comment]
The Typing Council does not have a standing delegation, merely an advisory role. That might still be worth mentioning, but it's a different situation from packaging.

**Comment by ncoghlan** [comment]
Yeah, it would mean generalising the doc a bit, which is why I didn't just go ahead and make a PR - there's a genuine SC discussion/decision needed on whether the document *should* be generalised.

I'm thinking there would be two sections:

* Standing PEP Delegations: the existing PyPA delegations, which are explicitly default PEP delegations since decisions below the PEP level are typically handled by the individual open source projects affected by them rather than needing broad community consensus and a shared design direction
* Advisory Delegations: the Typing Council, C API working group, and Documentation Editorial Board, where groups of specialists are appointed by the SC to provide direction on complex topic areas where arguable design and editorial decisions frequently need to be handled, but PEP level decisions are rare enough that it still makes sense for the SC to handle them by default. When PEPs do come up, the SC will decide on a case by case basis whether or not it makes sense to delegate the final decision.

With the PEP categories on the modernised PEP index, I don't think it's a big deal (since the Governance PEP category is an even more obvious place to look for this info than the SC docs), it was just something that seemed worth making a note of.

**Comment by emilyemorehouse** [comment]
The Standing Delegations document was updated a few weeks ago in [this PR](https://github.com/python/steering-council/pull/261). It was kept a bit more high-level than @ncoghlan's suggestions, so please feel free to open a PR with further elaborations if you'd like to see more from this!
