### ISSUE TITLE
PEP 741 -- Python Configuration C API (updated)

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#246]
Please consider PEP 741 -- Python Configuration C API
https://peps.python.org/pep-0741/

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *Typing* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

---

Since my [first submission in March](https://github.com/python/steering-council/issues/237) (3 months ago), the PEP was discussed again and was updated to address Steering Council's review and reviews of other core developers.

* Describe interactions with PEP 587 PyConfig API.
* Exclude the API from the limited C API. Remove the rationale about the limited C API / stable ABI.
* Remove string types other than UTF-8: only keep UTF-8 string type, remove "locale" and "wide string" string types
* Remove PyInitConfig_CreatePython() and rename PyInitConfig_CreateIsolated() to PyInitConfig_Create().
* Remove the explicit preconfiguration.
* Rejected Ideas: Add "locale encoding and wide strings".

**Comment by vstinner** [comment]
Did you have the opportunity to review the PEP 741 updated for your latest review?

**Comment by Yhg1s** [comment]
Not yet. It's still on our agenda, but more pressing things have taken priority of late. I'm not yet sure when we can get to it, given that our focus right now is 3.13, but hopefully in the next couple of weeks.

**Comment by warsaw** [comment]
Closing as [approved](https://discuss.python.org/t/pep-741-python-configuration-c-api-second-version/45403/88).
