### ISSUE TITLE
Add the current SC members and term limit to the README

### ISSUE THREAD

**Issue by srittau** [python/steering-council#252]
I was just googling "python steering council" and this repository was the first hit. While the README has a bit of information for casual visitors (especially the office hours), I think it could benefit from the list of current council members as well as the current term dates, ideally with links to the appropriate PEPs. (Although you can find this information by going to the very last PEP link at the very bottom of the page.)

**Comment by Jackenmen** [comment]
Funnily, I did the same thing a few hours ago too :smile: Ended up finding it in the PEP - same as you, it seems.

**Comment by hugovk** [comment]
It's defined in PEP 13.

The current SC: https://peps.python.org/pep-0013/#current-steering-council

The term and lack of term limits: https://peps.python.org/pep-0013/#term

> A new council is elected after each feature release. Each council’s term runs from when their election results are finalized until the next council’s term starts. There are no term limits.

The [README](https://github.com/python/steering-council#reference) already includes a link to PEP 13:

> * [PEP 13 Python Language Governance](https://peps.python.org/pep-0013/) (including [list of current Steering Council members](https://peps.python.org/pep-0013/#current-steering-council))

**Comment by gpshead** [comment]
I made a the PEP-13 link more prominent in the repo README.
