### ISSUE TITLE
Request to approve restoration of Emscripten to Tier 3 support

### ISSUE THREAD

**Issue by freakboy3742** [python/steering-council#256]
I would like to formally request the Steering Council's approval to restore Emscripten to Tier 3 support in CPython.

Emscripten and WASI were both Tier 3 platforms for the Python 3.12 release; however, early in the 3.13 timeframe, @brettcannon was no longer able to act as the core team sponsor of the Emscripten platform. He asked for other core team members to take up this role, but none were forthcoming; as a result, Emscripten was demoted to "not officially supported". 

I (@freakboy3742) am now offering to take on the role as core team sponsor. I have approval from my employer (Anaconda) to include review and management of Emscripten issues as part of my job description; I also have approval for Anaconda to provide hardware for a buildbot.

@hoodmane is a maintainer of Pyodide, and has indicated his desire to generate the patches necessary to restore, maintain and improve Emscripten support in CPython. 

There are others inside Anaconda who will be in a position to do informal testing and possibly contribute fixes through their work on PyScript.

In discussion with @brettcannon at the 2024 Core Team sprint, he suggested that a formal PEP for Tier 3 restoration wasn't necessary - partly because there wasn't a PEP for the original Emscripten/WASI work, but also because the code for Emscripten support still *exists*, it just isn't tested and validated by buildbots at this time. As a result, there's no large scale design issues to consider; it's more of a procedural decision around the PEP 11 status of Emscripten as a platform.

**Comment by Yhg1s** [comment]
The SC approves re-adding emscripten as a tier 3 platform. Thanks for taking on the burden :)

**Comment by brettcannon** [comment]
FYI I created the [`OS-emscripten` label](https://github.com/python/cpython/labels/OS-emscripten).

**Comment by hoodmane** [comment]
Can I attach the label to my prs and issues or are repo permissions needed?

**Comment by brettcannon** [comment]
> Can I attach the label to my prs and issues or are repo permissions needed?

I'm not sure, so I guess give a try?

**Comment by encukou** [comment]
I think you do need permissions.
Do you want to become a triager? If so, please read the [devguide](https://devguide.python.org/triage/) chapter on it; there won't be much news for you but some CPython repo specifics might be useful.

**Comment by hoodmane** [comment]
Yeah I think adding me as a triager would be helpful. It would reduce the amount of busy work I need to ask Russel to take care of by a bit.
