### ISSUE TITLE
Is it ok to delegate PEP 743 "Add Py_COMPAT_API_VERSION to the Python C API" to the C API Working Group?

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#259]
Hi,

@encukou and me authored [PEP 743: Add Py_COMPAT_API_VERSION to the Python C API](https://peps.python.org/pep-0743/). Are you ok with delegating it to the C API Working Group, or do you want to handle this PEP?

Victor

---

Note: I already used "PEP-Delegate: C API Working Group" on [PEP 756 – Add PyUnicode_Export() and PyUnicode_Import() C functions](https://peps.python.org/pep-0756/) and [PEP 757 – C API to import-export Python integers](https://peps.python.org/pep-0757/), but these two PEPs are special, they were already open issues in the C API WG decision project. I wrote PEPs to summarize the discussion.

**Comment by Yhg1s** [comment]
The SC discussed this and would rather not delegate the PEPs to the C API WG as a whole. I've just updated https://github.com/python/steering-council/blob/main/process/standing-delegations.md to reflect the relationship between the SC and the C API WG in this area, as described in PEP 731 (https://peps.python.org/pep-0731/#relationship-with-the-steering-council).

To avoid apparent conflicts of interest, the SC would rather deal with these PEPs by having the C API WG provide a recommendation (as normal), but not be the PEP-Delegates.

**Comment by vstinner** [comment]
Ok, I created https://github.com/python/steering-council/issues/264 for PEP 757 "C API to import-export Python integers".
