### ISSUE TITLE
PEP 757 -- C API to import-export Python integers

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#264]
Please consider PEP 757 -- C API to import-export Python integers
https://peps.python.org/pep-0757/

The C API Working Group is in favor of this PEP: https://github.com/capi-workgroup/decisions/issues/45

* [x] The PEP has been discussed in threads listed in its `Post-History` header
  
* [x] The PEP was announced on [Discuss](https://discuss.python.org/c/peps/19) (link in `Post-History`)
  
* [x] The PEP includes all relevant [Suggested Sections](https://peps.python.org/pep-0012/#suggested-sections)
* [x] The PEP includes endorsements from the projects/groups/people it helps
  
* [x] The PEP has a CODEOWNERS entry
  

SIG-specific:
* [ ] *Typing* PEPs: link to the [Typing Council](https://github.com/python/typing-council)'s recommendation for the PEP:
* [ ] *Packaging* PEPs: don't file the issue here, ask the delegate (Paul Moore) on [Packaging Discourse](https://discuss.python.org/c/packaging/14)

**Comment by gpshead** [comment]
The steering council has decided to accept PEP 757 per the C API Working Group's recommendation.  Thanks for drafting it with explanations as to why it is needed and providing usage examples.

_(and thanks for bearing with my own personal questions about the PEP and documentation requests which you turned into follow-up PRs!)_
