### ISSUE TITLE
.py gTLD

### ISSUE THREAD

**Issue by toddjames** [python/steering-council#27]
Python has grown to be quite a popular language. #2 by many counts, and still rising in popularity. A .py gTLD may allow for projects to have a unique presence on the internet. Imagine tensorflow.py, django.py, flask.py, numpy.py (or num.py), etc. all having their respective domains.

This could potentially also be open to developers that wish to register their moniker under the .py gTLD, which many may in order to market themselves.

I'm off on my own island over here, so please let me know if this is completely off-base or has been considered before.

**Comment by hugovk** [comment]
It already exists

> .py is the Internet country code top-level domain (ccTLD) for Paraguay.

But

... |... 
-- | --
Intended use | Entities connected with  Paraguay
Actual use | Fairly popular in Paraguay
Registration restrictions | Second-level registrations prohibited; must have a contact in Paraguay; subdomains have various restrictions; all applications subject to approval by registry




https://en.wikipedia.org/wiki/.py

**Comment by vstinner** [comment]
It seems like using the Paraguay TLD for Python projects would be an abuse of their policy. I don't think that the PSF should promote that. I'm fine with ".org" of python.org for example. I close the issue.
