### ISSUE TITLE
PEP 618: Self-Nomination for BDFL-Delegate

### ISSUE THREAD

**Issue by brandtbucher** [python/steering-council#28]
@gvanrossum has agreed to act as BDFL(-Delegate?) for [PEP 618](https://www.python.org/dev/peps/pep-0618/).

While PEP 1 states that such self-nominations are accepted by default and can be vetoed by the SC, it's otherwise quite vague. Beyond the PEP header, is there any requirement to communicate the decision to the SC or others? If so, how?

**Comment by gvanrossum** [comment]
I expect to have time to review PEP 618 later this week.

**Comment by warsaw** [comment]
I have no objection's to Guido serving as BDFL-Delegate for PEP 618.  I've added this agenda item to the Steering Council meeting for 2020-06-15.

**Comment by vstinner** [comment]
`BDFL-Delegate: Guido van Rossum <guido@python.org>` header was added to the PEP in https://github.com/python/peps/pull/1429 which was merged by Guido.

**Comment by warsaw** [comment]
True, but let's make it official, as pointed out by @brandtbucher

**Comment by gvanrossum** [comment]
At the very least please clarify the process. PEP 1 was not enough for Brandt and me to know how to proceed.

**Comment by brandtbucher** [comment]
Particularly confusing is this bit:

> However, content review and final acceptance of the PEP must be requested of the core developers, usually via an email to the python-dev mailing list.

The part about "final acceptance" just seems incorrect.

**Comment by warsaw** [comment]
The SC approves of @gvanrossum as PEP-Delegate for PEP 618.  We will also be updating the PEP 1 language to clarify the process.  Thank you!
