### ISSUE TITLE
Python 2 sunset preparation: docs.python.org deep links

### ISSUE THREAD

**Issue by ncoghlan** [python/steering-council#3]
The current handling of deep links on docs.python.org is covered by [PEP 430](https://www.python.org/dev/peps/pep-0430/):

* unqualified deep links resolve to the Python 2.7 documentation
* the canonical URL for up to date Python 3 documentation includes a `/3/` segment in the path

That approach made sense when I wrote PEP 430, but that's almost 7 years ago now, and there's the potential to ask the PSF for assistance in the somewhat tedious task of implementing a more sophisticated solution for adoption as part of the Python 2 sunsetting process (and also easing a possible future transition to a python 4.0 release if we ever decide to make one of those rather than continuing with double-digit minor versions in the 3.x series).

I'm not planning to write that PEP myself, but some potential ideas that it could cover:

* switching the canonical URL for the English Python documentation from "docs.python.org/3/" to "docs.python.org/en/" (in alignment with [PEP 545](https://www.python.org/dev/peps/pep-0545/))
* setting the canonical URL even on old maintenance branches that are otherwise no longer receiving documentation updates (either by making one final commit to them, or by amending the HTML files directly on the documentation hosting server)
* setting the canonical URL meta tag even in the Python 2.7 documentation to refer to the relevant "docs.python.org/en/" URL (but do the work to handle module renames and other moves correctly)
* adding a banner to end of life versions that clearly indicates that the specified version is no longer receiving security updates, and potentially also linking to the latest version (see https://docs.djangoproject.com/en/1.10/ref/django-admin/ for an example of such a banner, albeit without a direct link to more recent documentation)

**Comment by gvanrossum** [comment]
I don't think this discussion necessarily needs to be carried out in the SC's domain. Perhaps move these ideas to Discourse or python-ideas?

**Comment by ncoghlan** [comment]
The part that I think is in the SC's domain is the fact that unlike most things, this kind of has a deadline associated with it (i.e. the planned sunset date for Python 2.7).

But yeah, one possible resolution at our level is "No need to complete the work by any specific date, so just file it as a regular docs issue and see if anyone takes it up".

**Comment by gvanrossum** [comment]
I don't see how the SC can make this happen faster, unless we volunteer to
do it ourselves -- but I just don't see the priority. The sky isn't falling
even if we don't do this.

**Comment by warsaw** [comment]
I concur.  I don't think there's much for the SC to do, unless there's some objection to making the Python 3 documentation "the default".  But that's an easy pronouncement. :)

**Comment by brettcannon** [comment]
Let's start with the discussion out in the open and then we can act as tiebreaker if necessary.

**Comment by brainwane** [comment]
Followup to this [and the SC's July update](https://github.com/python/steering-council/blob/master/updates/2019-07-08_steering-council-update.md) for other folks reading along: The PSF has hired [Changeset Consulting](https://changeset.nyc/) (my firm) to do a bunch of documentation updates on python.org, to improve communication about the sunsetting. [More details on my blog.](https://www.harihareswara.net/sumana/2019/08/05/0)

**Comment by ned-deily** [comment]
If you are planning to make changes to the cpython docs, you should ensure that the release managers (@benjaminp et al) and our release documentation expert (@JulienPalard) are reviewing  any PRs and discussion about them to ease their adoption and minimize long-term maintenance issues.  In particular, I'm wondering if there's a reason why @leonardr in the message above appears to create a PR to their own clone; if it's going to go into cpython, the PR needs to be made against the python/cpython repo.

**Comment by brainwane** [comment]
Thanks for the guidance.

Leonard deliberately created that PR against his own fork so I could review it first, by the way.

**Comment by JulienPalard** [comment]
Thanks @ned-deily for the heads up, I'm not following issues of the SC repo.

@brainwane: I implemented the deprecation header a year ago (https://github.com/python/cpython/commit/46ed90dd014010703c7a3b2a61c4927644fa8210), documented it in the [Doc/README.rst file](https://github.com/python/cpython/tree/master/Doc#deprecation-header) and we're already using it in production for some old releases like https://docs.python.org/3.4/.

**Comment by leonardr** [comment]
Julien, thank you for the guidance and for the work you've already done. I've put up https://github.com/python/cpython/pull/19229, which backports your work to 2.7 and incorporates the wording change made later (changing "last" to "current").

I have two remaining concerns. First, the deprecation notice is general; for 2.7 the thinking was we'd have a message that linked to the sunsetting document. Should we change the string (creating more translation work) or leave it consistent across versions?

The second concern is probably just a point of information: I don't understand how the `html_context` is populated. On python.org I see this banner for 3.4, but not any other version, and I don't see any branch that defines `html_context` in its `Doc/conf.py` file. So I'm assuming `html_context` is populated during the documentation build process. I looked at the docsbuild-scripts projects and didn't see it mentioned there. I'm sure this is just my ignorance speaking, but want to make sure there's nothing missing from my PR.

**Comment by JulienPalard** [comment]
> I have two remaining concerns. First, the deprecation notice is general; for 2.7 the thinking was we'd have a message that linked to the sunsetting document. Should we change the string (creating more translation work) or leave it consistent across versions?

I'd prefer consistency between versions, and a simple message, over personalisation, but I'm not against linking to a cross-version-"sunsetting info" page from every versions, maybe simply https://devguide.python.org/#status-of-python-branches, or a more specific one. If we go for https://devguide.python.org/#status-of-python-branches, a link from it to the 2.7-sunsetting page can be added for discoverability.

> The second concern is probably just a point of information: I don't understand how the `html_context` is populated. On python.org I see this banner for 3.4, but not any other version, and I don't see any branch that defines `html_context` in its `Doc/conf.py` file. So I'm assuming `html_context` is populated during the documentation build process.

Right, I admit the README goes a bit fast about it, sorry.

> I looked at the docsbuild-scripts projects and didn't see it mentioned there.

The 3.4 doc is no longer automatically built, so I think the 3.4 documentation was just manually built with a `make autobuild-stable SPHINXOPTS='-D html_context.outdated=1'`, one last time, to add the banner.

For 2.7 it can be added from docsbuild_scripts, I have it in my todo list but low priority util 2.7.18, I did not wanted to rush a big red banner on 2.7. So you can either PR it or leave it in my todo list :)

**Comment by vstinner** [comment]
I like the idea of a single banner for all Python versions which are no longer supported. I also like the idea of pointing to a single web page which gives the status of all branches.

https://devguide.python.org/#status-of-python-branches can easily be modified to add a link to https://www.python.org/doc/sunset-python-2/ for Python 2.

**Comment by leonardr** [comment]
Thanks for the guidance, @JulienPalard and @vstinner. I've got two PRs which I believe get us to a good place. There's a small amount of additional work which we can do either now or later.

https://github.com/python/cpython/pull/19229, which we've already discussed, adds the header if the `outdated` template variable is set. I've changed the header so it links to https://devguide.python.org/devcycle/#end-of-life-branches, a stable URL that will explain the situation for any branch that has reached end-of-life, without making it necessary to modify the devguide's `index.rst`.

https://github.com/python/docsbuild-scripts/pull/86, which I just created, changes the doc build process so that the `outdated` template variable is set when building documentation for 2.7 releases.

The additional work I refer to would be to modify [the devguide's `devcycle.rst`](https://github.com/python/devguide/blob/master/devcycle.rst) (the source for https://devguide.python.org/devcycle/#end-of-life-branches) to give it a link to the Python 2 sunset document. I can put up a PR for this if someone can give recommendations on copy and placement.

**Comment by pradyunsg** [comment]
Since https://devguide.python.org/devcycle/#end-of-life-branches links to [PEP 373](https://www.python.org/dev/peps/pep-0373/#update), would it make sense to update PEP 373, to link to https://www.python.org/doc/sunset-python-2/?

**Comment by leonardr** [comment]
I think it definitely makes sense to update PEP 373, which currently talks about the sunset in the future tense. But if we make that change instead of changing the devguide, I don't think readers will realistically carry out the navigation steps necessary to get to the sunsetting document from a random Python documentation page:

https://docs.python.org/2.7/library/os.html →
https://devguide.python.org/devcycle/#end-of-life-branches →
https://www.python.org/dev/peps/pep-0373/#update →
https://www.python.org/doc/sunset-python-2/

We started with a design where a reader who learned something distressing was one click away from a document written to address their concerns. Now they're two, maybe three clicks away. How important is it that that people get to this document? The fact that we wrote it at all makes me think it's important enough that we should put links in PEP 373 _and_ in the devguide.

**Comment by pradyunsg** [comment]
Oh, I wasn't suggesting that as an alternative to updating the dev guide, but rather to have consistent communication across all these locations.

**Comment by leonardr** [comment]
Sorry for the misunderstanding. Yes, updating the PEP as well is a great idea.

**Comment by brainwane** [comment]
Steering Council and @ejodlowska - I am concerned that https://github.com/python/cpython/pull/19229 may not be reviewed and merged before the April 18th date on which 2.7 will be finalized and the branch closed. If you could take a look, I'd appreciate it. Thanks.

**Comment by brettcannon** [comment]
@brainwane is there a release blocker issue on bugs.python.org for this?

**Comment by brainwane** [comment]
@brettcannon Creating one now. Thank you.

**Comment by brainwane** [comment]
Done: https://bugs.python.org/issue40311

**Comment by brainwane** [comment]
@ncoghlan We've now completed the Python 2 sunsetting-specific work, so I suggest we close this issue and move the longer-term documentation setup/process work to the issue tracker that's more appropriate - as you said, file it as a regular docs issue.
