### ISSUE TITLE
Submission for SC consideration: PEP 622 "Structural Pattern Matching"

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#33]
[PEP 622](https://www.python.org/dev/peps/pep-0622) has gone through extensive review -- we posted a first draft on June 23rd and a second, greatly improved one, on July 8th (a week ago today). While the first draft spawned intense pushback, the second draft has been mostly received positively, with the exception of Mark Shannon -- but we feel Mark's criticism has been adequately responded to.

We now seek approval from the Steering Council, either directly or through the appointment of a PEP-Delegate. We are happy to answer any questions about the PEP -- we understand it's a long one and some fine points may be somewhat buried. We also understand the SC has a backlog of decisions and may not be able to give us a decision in the next few weeks, but we are hoping for a decision in time for the first 3.10 alpha release.

For SC members who haven't followed the debate, probably the best way to get into it is to start reading my [cover letter](https://mail.python.org/archives/list/python-dev@python.org/message/LOXEATGFKLYODO5Y4JLSLAFXKIAMJVK5/) for the 2nd version, and then just read the [PEP](https://www.python.org/dev/peps/pep-0622/) itself (it starts with an overview that should be easy to follow).

We are of course also happy to make changes to the PEP based on feedback from the SC. In particular there are a couple of somewhat controversial issues left:

- The indentation scheme. We think that the current proposal has the least surprises, but we understand not everybody likes it.
- Whether to add an `else:` clause. We favor to use `case _:` here, and there is considerable debate about the indentation of the `else` clause if it were to be added.
- How to indicate the difference between "load" (for value patterns) and "store" (for capture patterns). We currently favor using an unqualified name for stores[1] and making qualified (i.e., dotted) names for loads, since this appears to us to be the cleanest scheme of all, and in most cases stores will greatly outnumber (unqualified name) loads. But some folks seem to be keen on having *some* notation to load an unqualified name. Many competing proposals have been made, but none that look very satisfying. Fortunately it's easy to add one of these in the future if we find that the need is strong (which we don't anticipate).
- How to spell wildcards. The PEP authors strongly believe that `_` is the right choice here. A few readers have objected to this (because it can't work *exactly* the way `_` works in assignment targets) and proposed other notations. Most recently Larry Hastings' proposed using `?`. In his final message on the topic he seems to at least agree that it's not easy to make everyone happy and said he wouldn't pursue it further.

[1] This follows the lead of the walrus operator (PEP 572). We also follow its lead in not establishing new scopes for capture variables.

**Comment by brettcannon** [comment]
I've put the PEP on the agenda for our next meeting, but we are obviously dealing with a lot of stuff as you acknowledged, @gvanrossum . It looks like 3.10a1 is slated for October 5.

**Comment by gvanrossum** [comment]
Closed in favor of #39.
