### ISSUE TITLE
Requesting a formal statement from the SC on politics in commit messages

### ISSUE THREAD

**Issue by Rosuav** [python/steering-council#34]
#31 has stated that the offending commit message (and I use those words deliberately) will not be edited. However, there is still the open question of what will be accepted in the future. If nothing is done or said, the SC is effectively declaring that this commit message is perfectly acceptable and similarly barbed messages will be fully welcomed.

I request a deliberate and formal statement from the SC on this matter. If the stance is "we deplore this message, but would more strongly deplore the consequences of editing git history", then that would at least make a clear statement for the future. On the other hand, if you *do* accept the tone of this message, please make that clear.

Commit messages are normally an internal detail, and most advice on how to write them is focused on clarity and readability, not on what's appropriate. But this one has gotten itself into a very public position.

**Comment by aeros** [comment]
+1, I think it would be highly beneficial to have a public announcement from the SC to briefly explain whether or not politically-charged messages are something we want to accept going forward (which I'm personally against, more details [here](https://github.com/python/steering-council/issues/31#issuecomment-653379718)). With the continuous growing popularity of Python and increase in people interested in contributing, a scenario like this seems very likely that it could occur again in the future.

IMO, it will go over much more smoothly in those future scenarios if we have something to point to that's a bit more definitive than ["The SC met today and have decided we are not going to be editing the commit message, although some on the SC suggested they probably would have tried wordsmithing it a bit before merging the PR"](https://github.com/python/steering-council/issues/31#issuecomment-661267744), and public facing as a formal statement on somewhere like python-dev. 
The SC repo's issue tracker is significantly less visible and will be missed even by active contributors to CPython.

> If nothing is done or said, the SC is effectively declaring that this commit message is perfectly acceptable and similarly barbed messages will be fully welcomed.

I mostly agree, but think it's more so establishing that "the commit message was generally acceptable, but could have been better". That's not quite the same as welcoming similar commit messages, but it does nothing to deter them. Either way, neither of those are precedents that I'd like to see established.

**Comment by brettcannon** [comment]
I wanted to say that I am going to be unsubscribing from this issue and only be addressing it personally for the SC from the question of, "are we okay with the commit message in question, or would we have wanted to have seen it edited?" I'm doing this as the original phrasing is already showing bias by saying the message was "barbed" and not keeping it as a neutral question for us to answer which could lead to unconscious bias when discussing this. I also do not want to get sucked into yet another side discussion on this topic when I already read so many emails about it.

**Comment by warsaw** [comment]
Status update: we discussed this at today's SC meeting.  We are considering a formal statement, but we want to wait until the next meeting where we have a full compliment of members.  That will likely be two weeks from today.

**Comment by Rosuav** [comment]
Thank you.

**Comment by brettcannon** [comment]
The SC discussed this and we agree that even if it was easy to edit post-merge we would still leave the message as-is; we do not deplore the message.

We also agree that commit messages are meant to convey the reasons why a change was made.

We can't say whether we would have halted, edited, or done anything else to change the submission of the commit message.

**Comment by marekmosiewicz** [comment]
Is'nt software development about politics ? In not, why is there  so many languages here on the planet ?

**Comment by aeros** [comment]
Thank you for the update @brettcannon. While I'm not entirely content with the outcome (specifically that the commit message would have been left as-is, even if it was easy to change it), I appreciate the effort put forth in thoroughly reviewing the situation and in the releasing of a formal statement by the SC.

**Comment by jpic** [comment]
> We can't say whether we would have halted, edited, or done anything else to change the submission of the commit message.

Does that mean that the SC is going to hire people with a actual political science curriculum to review future commit messages making a political statement ?

> Isn't software development about politics ? In not, why is there so many languages here on this planet, not to mention frameworks and duplicated applications ?

It's not, politics is about organization of society, languages / frameworks is about organization of code.

**Comment by willingc** [comment]
Locking this thread since the Steering Council has responded to the issue.
