### ISSUE TITLE
Submission for SC consideration: PEP 612 "Parameter Specification Variables"

### ISSUE THREAD

**Issue by mrkmndz** [python/steering-council#35]
[PEP 612](https://www.python.org/dev/peps/pep-0612/) has been discussed and considered at length on the `typing-sig` list, since its first posting on December 19, 2019.  The latest version now includes the features and syntax changes requested by the community, and has a full reference implementation.

We now seek approval from the Steering Council, either directly or through the appointment of a PEP-Delegate.

We are more than happy to answer any questions, or make any changes to the PEP based on feedback from the SC.

cc @gvanrossum

**Comment by gvanrossum** [comment]
If the SC were to appoint me delegate, I would immediately approve this PEP, having carefully reviewed it already.

So to save some time the SC might consider just approving it.

**Comment by brettcannon** [comment]
I've added the PEP to the agenda for our next meeting.

**Comment by brettcannon** [comment]
Guido accepted this PEP the other day.
