### ISSUE TITLE
Submission for SC consideration: PEP 626 "Precise line numbers for debugging and other tools."

### ISSUE THREAD

**Issue by markshannon** [python/steering-council#36]
Initial feedback was mostly positive, but Pablo Galindo, Gregory Smith and Steve Dower brought up the issue of out-of-process debuggers and profilers.
I have address their concerns. Pablo and Ben Frederickson (author of py-spy) are happy with it now.

**Comment by brettcannon** [comment]
https://www.python.org/dev/peps/pep-0626/

I've added it to our next agenda, Mark, but just to warn you the agenda is already pretty packed and so I'm not sure when we will get around to talking about it.

**Comment by gpshead** [comment]
On Fri, Aug 14, 2020 at 9:51 AM Brett Cannon <notifications@github.com>
wrote:

> https://www.python.org/dev/peps/pep-0626/
>
> I've added it to our next agenda, Mark, but just to warn you the agenda is
> already pretty packed and so I'm not sure when we will get around to
> talking about it.
>
Feedback rereading the pep in its current form:

  Objections to co_lnotab becoming dynamically created in 3.10 and
ultimately going away in the future have been addressed via the new Out of
process debuggers and profilers section.  thanks!

small things:

"soure of truth"

  typo.  source of truth

"the f_lineno will be set to the line at which the function or class is
defined; that is the line on which the def or class keyword appears."

  Presumably add "lambda" to that list of keywords?

+1 overall

-gps

>

**Comment by lviggiano** [comment]
Can you people please reconsider the word "Submitting"? It reminds of slavery and white supremacy.

**Comment by brettcannon** [comment]
Pablo was named PEP delegate, so I'm closing this issue.
