### ISSUE TITLE
Submission for SC consideration: PEP 632 - Deprecate distutils module

### ISSUE THREAD

**Issue by zooba** [python/steering-council#38]
It's time :) (to formalise the informal deprecation of the last decade ;) )

https://www.python.org/dev/peps/pep-0632/

The discussion at https://discuss.python.org/t/pep-632-deprecate-distutils-module/5134 reads like a list of potential delegates, if nobody wants it for themselves.

**Comment by vstinner** [comment]
> The final dependency on distutils is CPython itself, which uses it to build native extension modules in the standard library (except on Windows). Because this is a CPython build-time dependency, it is possible to continue to use distutils for this specific case without it being part of the standard library.

Would it be possible to write a more concrete plan for this part?

* Do you plan to continue to use the deprecated distutils module to build C extension modules on Unix?
* How these C extensions will be built once distutils will be removed?
* Is there a plan to use setuptools for that? If yes, how will it be included in CPython?

**Comment by zooba** [comment]
My plan is to keep using the deprecated distutils module for Unix. If we reach removal and nobody else has worked on an alternate approach, then we keep using it but stop shipping it.

Some other people have expressed an interest in moving the extension modules to be built in the makefile. I am neither opposed to this, nor volunteering to do it myself.

I don't expect to ever use setuptools in the CPython build.

**Comment by brettcannon** [comment]
I just announced on python-dev the acceptance of this PEP!
