### ISSUE TITLE
For SC consideration: PEP 634 and PEP 635, Pattern Matching

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#39]
This replaces #33.

The implementation is shaping up nicely (Pablo has volunteered to review) and we're hoping to land this in 3.10 alpha 3, slated for December 7.

I just sent an [announcement to python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/Q4BU4XMNOVUW6Y2OGXZB6RAQRRQKWAOU/).

As discussed, we abandoned the old PEP 622 and broke it up into three parts:

- [PEP 634](https://www.python.org/dev/peps/pep-0634/): Specification
- [PEP 635](https://www.python.org/dev/peps/pep-0635/): Motivation and Rationale
- [PEP 636](https://www.python.org/dev/peps/pep-0636/): Tutorial

Of these, PEP 636 is informational, and at this point there's probably nothing new for the SC members. The other two are meant to be read side by side, where PEP 634 gives the pure specification and PEP 635 gives the rationale for each design decision, including discussion of alternatives considered. We're really only asking for approval of the specification (PEP 634).

A TL;DR of substantial changes (I hope I didn't miss anything):

- We changed walrus patterns ('v := p') to AS patterns ('p as v').
- We changed the method of comparison for literals None, False, True to use 'is' instead of '=='.
- SyntaxError if an irrefutable case[1] is followed by another case block.
- SyntaxError if an irrefutable pattern[1] occurs on the left of '|', e.g. 'x | [x]'.
- We dropped the `@sealed` decorator and everything aimed at static type checkers.

[1] An irrefutable pattern is one that never fails, notably a wildcard or a capture. An irrefutable case has an irrefutable pattern at the top and no guard. Irrefutability is defined recursively, since an '|' with an irrefutable pattern on either side is itself irrefutable, and so is an AS pattern with an irrefutable pattern before 'as'.

The following issues were specifically discussed with the SC previously:

- Concerns about side effects and undefined behavior. There's now some specific language about this in a few places (giving the compiler freedom to optimize), and a section "Side Effects and Undefined Behavior".

- Footgun if `case NAME:` is followed by another case. This is now a SyntaxError.

- Adding an 'else' clause. We decided not to add this; motivation in PEP 635.

- Alternative 'OR' symbol. Not changed; see PEP 635.

- Alternative wildcard symbol. Not changed, but Thomas wrote PEP 640 which proposes '?' as a general assignment target. PEP 635 has some language against that idea.

- Alternative indentation schemes. We decided to stick with the original proposal; see PEP 635.

- Marking all capture variables with a sigil. We all agreed this was a bad idea; see PEP 635.

**Comment by gvanrossum** [comment]
In case you are asked to consider PEP 642, we have added some text to our PEP 635 explaining our position on it (https://github.com/python/peps/pull/1691/files). There is also some text (In the wildcard section of PEP 635) about PEP 640.

**Comment by brettcannon** [comment]
In our meeting today and we decided that while SC 2020 doesn't feel comfortable making a final decision on these PEPs with the election being so close, we do plan to make an official, serious recommendation for the next SC in regards to these PEPs and let SC 2021 make the final decision.

**Comment by ncoghlan** [comment]
The 3rd and largely final (modulo SC feedback and any outright bugs that reviewers find) iteration of PEP 642 is up: https://www.python.org/dev/peps/pep-0642/

It's very different from the first iteration that I posted, so it would make sense to update the comments about it in PEP 635 now that the design is no longer a moving target.

**Comment by gvanrossum** [comment]
> update the comments about it in PEP 635 

Done.

**Comment by gvanrossum** [comment]
Since this was accepted, I'm closing this issue.
