### ISSUE TITLE
PEP review request: PEP 570 -- Python Positional-Only Parameters

### ISSUE THREAD

**Issue by pablogsal** [python/steering-council#4]
We have recently finished the latest touch to the document for PEP 570 and we wish for the steering council to review it. Here is the document:

https://www.python.org/dev/peps/pep-0570

Here are some questions:

* Can we suggest a PEP-delegate? If that is possible, we would like Guido van Rossum to be the PEP-delegate.

* Should we submit the PEP document to python-dev or open a discourse topic for it?

**Comment by gvanrossum** [comment]
If the rest of the SC doesn't object I am happy to be BDFL-D for this.

I am willing to give Discourse a try on this, as long as you start me off
with a pointer to the initial post.

Do we have a convention for linking to Discourse in the Discussions-To
header?

**Comment by pablogsal** [comment]
I have created the post on discourse:

https://discuss.python.org/t/pep-570-python-positional-only-parameters/1078

Please, feel free to edit the initial post at will :)

**Comment by warsaw** [comment]
+1 for Guido as Delegate.

I seem to remember that there is at least one PEP with a Discussions-To pointing to Discourse.  Maybe @ncoghlan remembers which one it is.

**Comment by brettcannon** [comment]
I think I've come across one. I would just paste in the URL to the topic for the `Discussions-To` field.

**Comment by brettcannon** [comment]
And I don't object w/ Guido being listed as the BDFL Delegate.

**Comment by pablogsal** [comment]
I have sent an email to python-dev to inform and redirect people to discourse to avoid fragmenting the debate:

https://mail.python.org/pipermail/python-dev/2019-March/156908.html

**Comment by ncoghlan** [comment]
+1 for Guido as BD.

**Comment by gvanrossum** [comment]
I am now officially BDFL-Delegate for PEP 570. I will accept the PEP after @pablogsal has made the updates I requested on Discourse (https://discuss.python.org/t/pep-570-python-positional-only-parameters/1078/138).

**Comment by pablogsal** [comment]
We have finished the latest style and minor structural edits that we wanted to make and we have incorporated the requested sections. The changes are already visible in the web version of the document:

https://www.python.org/dev/peps/pep-0570/

**Comment by warsaw** [comment]
LGTM!

**Comment by gvanrossum** [comment]
I am waiting for https://github.com/python/peps/pull/975 and then I am ready to accept the PEP. Congrats!

**Comment by gvanrossum** [comment]
Accepted! See https://github.com/python/peps/pull/977
