### ISSUE TITLE
How to submit documents relating to a PEP for consideration by the SC?

### ISSUE THREAD

**Issue by markshannon** [python/steering-council#41]
Currently there is no way to submit comments or documentation relating to a particular PEP to the SC for consideration.
Posting to python-dev can easily degenerate into a shouting matching or worse.
I was subjected to personal abuse when making a purely technical objection to PEP 526.
Discussion relating to PEP 622 and PEP 634 is much better, but can still be quite wearing.

It also seems unreasonable to expect the SC to review in detail every email sent to python-dev, but a superficial analysis merely encourages more shouting, as 10 "me too" emails will drown any attempt as reasoned debate or formal analysis.

What is the best way to submit documents?

**Comment by warsaw** [comment]
You can always send a link to any documentation to `steering-council@python.org`.  The SC are the only members of that mailing list, so it's as private as it gets.

**Comment by brettcannon** [comment]
I would like to note that everyone sending us personal notes also doesn't scale for the SC. If there are duplicate concerns that are sent in privately then we duplicated what we have to sift through. Plus we then have to potentially care out multiple, separate conversations.

This isn't to say that people can't or shouldn't contact us privately, but I don't think it should be the primary way people typically discuss PEPs with us.

And if you suffered personal abuse, Mark, then please report it to the Conduct WG so it can be handled appropriately.

**Comment by brettcannon** [comment]
Closing as the SC agrees with the response Barry and I left.

**Comment by markshannon** [comment]
Just to clarify, sending an email to `steering-council@python.org` is the preferred way to submit anything for consideration?

**Comment by brettcannon** [comment]
@markshannon yep
