### ISSUE TITLE
Submission for SC consideration: PEP 637 - Support for indexing with keyword arguments

### ISSUE THREAD

**Issue by stefanoborini** [python/steering-council#45]
This issue opens up for consideration [PEP 637 - Support for indexing with keyword arguments](https://www.python.org/dev/peps/pep-0637/), with sponsor Steven D'Aprano. The proposal is the result of concerted effort on python-ideas and various requests to add keyword arguments to indexing operations, and replaces the five years old [PEP 472](https://www.python.org/dev/peps/pep-0472/) proposal. 

A side effect of the implementation of this PEP is the handling of tuple unpacking, which is of particular relevance for [PEP 646 - Variadic Generics](https://www.python.org/dev/peps/pep-0646)

A prototype, not reviewed but functional implementation is available at the address in Ref. 9 of the PEP.

**Comment by brettcannon** [comment]
As covered by https://www.python.org/dev/peps/pep-0001/#pep-review-resolution, a PEP needs to go to python-dev or discuss.python.org with an announcement email on python-dev before we can consider pronouncing on it.

**Comment by gvanrossum** [comment]
A brief discussion on python-dev should be simple enough. This PEP has been vetted thoroughly on python-ideas (I consider it one of the successes of that list) so I doubt that python-dev will have much pushback that isn't already addressed in the PEP. But of course we will follow the procedure!

**Comment by stefanoborini** [comment]
All right! Will do. Thanks.
