### ISSUE TITLE
Submission for SC consideration: PEP 648 Extensible customizations of the interpreter at startup

### ISSUE THREAD

**Issue by mariocj89** [python/steering-council#46]
After some feedback in [discourse](https://discuss.python.org/t/pep-648-extensible-customizations-of-the-interpreter-at-startup/6403) I want to submit PEP 648 for the SC consideration. I'm not a core dev, this PEP submission is sponsored by @pablogsal.

PEP: https://www.python.org/dev/peps/pep-0648/

Thanks!

**Comment by brettcannon** [comment]
I have added the PEP to our agenda, but we do have a backlog so it might be a little while before we get back to you.

**Comment by mariocj89** [comment]
Thanks! There is no rush here, whatever time it takes.

**Comment by Yhg1s** [comment]
The PEP was rejected: https://mail.python.org/archives/list/python-dev@python.org/message/UHODNOGISLYUKX2K2JCCBYMZFEWZDSPO/
