### ISSUE TITLE
Submission for SC consideration: PEP 637 - Support for indexing with keyword arguments

### ISSUE THREAD

**Issue by stefanoborini** [python/steering-council#47]
This issue opens up for consideration [PEP 637 - Support for indexing with keyword arguments](https://www.python.org/dev/peps/pep-0637/), with sponsor Steven D'Aprano. The proposal is the result of concerted effort on python-ideas and various requests to add keyword arguments to indexing operations, and replaces the five years old [PEP 472](https://www.python.org/dev/peps/pep-0472/) proposal. 

A side effect of the implementation of this PEP is the handling of tuple unpacking, which is of particular relevance for [PEP 646 - Variadic Generics](https://www.python.org/dev/peps/pep-0646)

A prototype, not reviewed but functional implementation is available at the address in Ref. 9 of the PEP.

The feature has been discussed on python-dev at the following thread

https://mail.python.org/archives/list/python-dev@python.org/thread/E3AMOIB3GKYAGN6IVSLEEKVP4VUEC2V3/

The general feedback is in favour of the PEP proposal, with no major objections. A last minute addition was performed to clarify the narrative to teach the feature to a typical "new to python" course audience.

**Comment by brettcannon** [comment]
I've added this to our next agenda, @stefanoborini , but unfortunately it's already packed, so it may be a while before we get around to talking about your PEP.

And thanks for sending it to python-dev!

**Comment by stefanoborini** [comment]
No problem. There's no hurry. I'll keep the prototype implementation branch collision free every now and then. Thanks.

**Comment by Yhg1s** [comment]
Thanks for the submission, but the SC has decided to reject the proposal: https://mail.python.org/archives/list/python-dev@python.org/thread/6TAQ2BEVSJNV4JM2RJYSSYFJUT3INGZD/
