### ISSUE TITLE
Submission for SC consideration: PEP 624 Remove Py_UNICODE encoder APIs

### ISSUE THREAD

**Issue by methane** [python/steering-council#48]
This issue opens up for consideration [PEP 624 - Remove Py_UNICODE encoder APIs](https://www.python.org/dev/peps/pep-0624/).

This PEP has been discussed in [python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/THXVM7FZVT56B7CPEDIYKJG6VMAYIEK5/#QUGBVLQNBFVNX25AEIL77WSFOHQES6LJ). I believe all points in the discussion is summarized well in the PEP.

(Since target version is Python 3.11, feel free to defer consideration and prioritize other PEPs targeting Python 3.10.)

**Comment by brettcannon** [comment]
I've added this to our agenda, but to be honest we probably won't get to it for a couple weeks as we have 3 other PEPs on top of other business ATM.

**Comment by Yhg1s** [comment]
Thanks for the PEP; the SC is happy to accept it, with two minor conditions: https://mail.python.org/archives/list/python-dev@python.org/thread/DR6YTABJ2UHC2HB2EY7R6NJO3OKXNPJN/
