### ISSUE TITLE
Submission for SC consideration: PEP 597 Add optional EncodingWarning

### ISSUE THREAD

**Issue by methane** [python/steering-council#49]
This issue opens up for consideration [PEP 597 -- Add optional EncodingWarning](https://www.python.org/dev/peps/pep-0597/).

This PEP has been discussed in discuss.python.org and python-dev. The latest thread is here:

* https://mail.python.org/archives/list/python-dev@python.org/thread/SFYUP2TWD5JZ5KDLVSTZ44GWKVY4YNCV/

Older threads for previous versions of the PEP (oldest first):

* https://discuss.python.org/t/use-utf-8-as-default-text-file-encoding/1785/17
* https://discuss.python.org/t/pep-597-use-utf-8-for-default-text-file-encoding/1819
* https://discuss.python.org/t/pep-597-enable-utf-8-mode-by-default-on-windows/3122
* https://discuss.python.org/t/pep-597-emit-a-warning-when-encoding-is-omitted/3880

**Comment by brettcannon** [comment]
I have added this to our agenda, but the rate of PEP submissions is not slowing down, so our backlog is pretty big. As such, I have no ETA on when we will start discussing this.

**Comment by Yhg1s** [comment]
Thanks for the submission. The SC is happy to accept this, and hopes to see more proposals along this line ;) https://mail.python.org/archives/list/python-dev@python.org/thread/YIZGJBMDQAOZHD6MXQCLEXIAKGUQFMQM/
