### ISSUE TITLE
PEP 554: request for BDFL-delegate

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/steering-council#5]
[PEP 554](https://www.python.org/dev/peps/pep-0554/) has mostly been in a holding pattern since the middle of last year (due to the governance transition).  It has been ready for pronouncement pretty much that whole time and really hasn't changed since before that (other than typos, formatting, and minor clarifications).  As noted in the PEP, the implementation is mostly complete.

At this point I'd like to get the process rolling again for pronouncement.  From what I understand that means requesting a BDFL-delegate.  (I do not have anyone to recommend.)

**Comment by gvanrossum** [comment]
The delegate is Antoine Pitrou. https://github.com/python/peps/commit/391c743cf2d113dd2baf67916814124faee5735d#diff-6e19d1f06f2eecc6c3b3199e69ff34e6
