### ISSUE TITLE
Submission for SC consideration: PEP 652 -- Maintaining the Stable ABI 

### ISSUE THREAD

**Issue by encukou** [python/steering-council#51]
This issue opens up for consideration [PEP 652 -- Maintaining the Stable ABI](https://www.python.org/dev/peps/pep-0652/).

This PEP has been discussed on [Discourse](https://discuss.python.org/t/pep-652-maintaining-the-stable-abi/6986) and before that on [capi-sig](https://mail.python.org/archives/list/capi-sig@python.org/thread/PMM5QG4IAL6LOMNFXNHW72INSCN4JC5H/).

I understand that the SC's backlog is big this time of year. Just putting the PEP on y'all's radar :)

**Comment by pablogsal** [comment]
I have added this PEP to our agenda, but the amount of pending PEP requests is high so our backlog is pretty big and therefore is difficult to say when we will start discussing this. The PEP targets 3.10, is there a time-specific constraint you want to consider?

**Comment by encukou** [comment]
No rush. While getting it in 3.10 would be nice, 3.11 would also work. This is a long game.

But now that I think about it, this could theoretically even be go in during the beta phase. There's no actual behavior change – just clarification of an under-specified feature, tests, docs, policy, advice.
