### ISSUE TITLE
Docs WG Google docs seems to be editable by anyone?

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/steering-council#53]
I'm seemingly able to open the link to the Docs WG Google docs provided here
https://github.com/python/steering-council/blob/master/updates/2021-01-steering-council-update.md#january-11
in incognito mode and edit it.

I haven't done anything mean (I promise!) but I suggest changing the sharing policies in the docs in case someone else does...

CC @willingc

**Comment by bskinn** [comment]
It looks like I don't even have to go into incognito mode to edit! 😬

**Comment by Fidget-Spinner** [comment]
Yeah seems to be anyone right now :(.

**Comment by willingc** [comment]
Thanks for the heads up. The file should be restricted now.

**Comment by Fidget-Spinner** [comment]
Yup, I just checked. Thanks Carol!

**Comment by willingc** [comment]
Thank you @Fidget-Spinner. I appreciate the heads up and you rechecking.
