### ISSUE TITLE
Submission for SC consideration: PEP 647 -- User-Defined Type Guards

### ISSUE THREAD

**Issue by erictraut** [python/steering-council#58]
Please consider [PEP 647](https://www.python.org/dev/peps/pep-0647/) for inclusion in Python 3.10.

The PEP has been discussed at length in the typing sig [here](https://mail.python.org/archives/list/typing-sig@python.org/thread/I3BPPNR53VK7X7B2HOI6VX3JLGA73DPK/) and [here](https://mail.python.org/archives/list/typing-sig@python.org/thread/NOLCFYLYAQQHXISNMPYCEOAZ7ZPFCGUW/) and in the python-dev mailing list [here](https://mail.python.org/archives/list/python-dev@python.org/thread/NOLCFYLYAQQHXISNMPYCEOAZ7ZPFCGUW/). 

Reference implementations have been created in both Mypy and Pyright.

**Comment by brettcannon** [comment]
I've added this to our agenda, @erictraut , but we are a bit backed up with tasks so I don't know when we will get to discussing the PEP.
