### ISSUE TITLE
PEP 578: Request for delegate

### ISSUE THREAD

**Issue by zooba** [python/steering-council#6]
I'd like to request a delegate to review and pronounce on PEP 578. I don't have anyone in particular in mind.

* https://github.com/python/peps/blob/master/pep-0578.rst
* https://www.python.org/dev/peps/pep-0578/ (couple minor PRs still in flight)

My implementation against master is at https://github.com/python/cpython/pull/12613

**Comment by gvanrossum** [comment]
The delegate is Christian Heimes. https://github.com/python/peps/commit/c1f8c85e6a22b864b64df9ce9e69fbe6f62bd201#diff-9a603f9a3af0aed3f2bedbd0fb385a5d
