### ISSUE TITLE
Submission for SC consideration: PEP 467 - Minor improvements to binary sequences

### ISSUE THREAD

**Issue by ethanfurman** [python/steering-council#62]
I am submitting [PEP 467](https://www.python.org/dev/peps/pep-0467/) for review by the SC in hopes that it can make it in to 3.10.  I do have an email out to @ncoghlan  to see if he has any objections to the last two minor changes I made.

Most of the code and tests are already written.

Thank you for your time!

**Comment by brettcannon** [comment]
I will add it to our agenda, although there's a bit of a backlog at the moment.

**Comment by ncoghlan** [comment]
I replied to the python-dev thread with a +1, but noting explicitly for the SC that I'm happy with Ethan's resolution of the previously open questions.

**Comment by ethanfurman** [comment]
I'm going to postpone this to 3.11 -- not enough time to integrate the existing code and get a couple more Enum improvements in. 

I'm not sure what to do with this PR.

Thank you!

**Comment by ethanfurman** [comment]
Withdrawing for the moment, will resubmit in the hopefully near future.
