### ISSUE TITLE
Submission for SC consideration: do all standard library modules abide by standard library policies

### ISSUE THREAD

**Issue by asottile** [python/steering-council#68]
Many standard library modules do primary development outside of the cpython codebase, some examples are `importlib.metadata`, `importlib.resources`, `zoneinfo`.  [PEP 387 - Backward Compatibility Policy](https://www.python.org/dev/peps/pep-0387/) does not differentiate these modules from others and so I am requesting clarity as to whether these policies apply equally to all standard library modules

Some context on this proposal is available in [bpo-44246](https://bugs.python.org/issue44246) where I have brought up that the breaking changes and aggressive deprecations in the proposed changes to `importlib.metadata` in python 3.10 do not align with the [backwards compatibility policy](https://www.python.org/dev/peps/pep-0387/#making-incompatible-changes) for the standard library

`importlib.metadata` has received significant adoption as it provides much more performant and widely available access to metadata than `pkg_resources` does -- it's been touted as "the one way to do it" in part because of its inclusion in the standard library.  it's an important piece of the import machinery.  I have also contributed significantly to its adoption through important improvements to flake8, pytest, tox, and others as well as encouragement through educational resources.  It's usage in setuptools, virtualenv, and other pypa tools is a testament to its popularity and stability.

my primary concerns with this module are:
- the types which were returned in previous versions have changed in incompatible ways
    - this makes it difficult to target both python3.8, python3.9, and the proposed python3.10 with a single-source codebase as there are not functionalities present in all three versions which are not in some way broken or deprecated due to the changes in python 3.10
    - the types *are part of the public interface* and a change there should not be taken lightly (in other standard library modules I believe this alone would be enough to cause a release blocker)
- this is not the first time similar development behaviour has caused significant breakage, causing a [release blocker in 3.9b2](https://bugs.python.org/issue40924) for example

my concrete asks are:
- standard library modules are treated as standard library modules independent of how they are developed
- clarify that all standard library modules are subject to the deprecate for two releases then remove policy
- importlib.metadata's provisional status is lifted given its ubiquitous adoption
- the breaking changes in importlib.metadata are reversed for 3.10

**Comment by gaborbernat** [comment]
I second the request for clarity on this topic. I'd like to have a document for all components shipped with CPython and their deprecation policies. Thanks 😊

**Comment by pablogsal** [comment]
Thanks for reaching out @asottile, I am adding this to our agenda.

**Comment by brettcannon** [comment]
To gather some links together:
- [PEP 360](https://www.python.org/dev/peps/pep-0360/) covers the externally maintained package policy.
- [PEP 411](https://www.python.org/dev/peps/pep-0411/) introduced provisional package acceptance.
- [`importlib.metadata` docs](https://docs.python.org/3/library/importlib.metadata.html#module-importlib.metadata)

**Comment by gaborbernat** [comment]
Shouldn't pip/seguptools be on the external packages list, as part of venv?

**Comment by brettcannon** [comment]
pip and setuptools don't count s they get pulled in independently by `venv`/`includepip`.

And sure, https://docs.python.org/3/library/zoneinfo.html#module-zoneinfo and https://docs.python.org/3/library/importlib.html#module-importlib.resources, but I mostly cared about the provisional status declaration for `importlib.metadata`.

**Comment by gaborbernat** [comment]
I guess my question was more around shouldn't we add ``zoneinfo`` to PEP-360. And even though venv/includepip pulls in I feel like pip/setuptools could/should be there too 🤔 but that's just me.

**Comment by brettcannon** [comment]
We discussed this in our latest meeting:

> standard library modules are treated as standard library modules independent of how they are developed

That was already true, so I don't think there's anything to clarify here.

> clarify that all standard library modules are subject to the deprecate for two releases then remove policy

That's covered by https://www.python.org/dev/peps/pep-0387/.

> importlib.metadata's provisional status is lifted given its ubiquitous adoption

We have asked Jason to do this.

> the breaking changes in importlib.metadata are reversed for 3.10

There's disagreement over whether the changes are breaking changes or not, but since the module was marked as provisional then the changes are within scope/guidelines as a provisional PEP. We won't be asking for a reversion.

> shouldn't we add zoneinfo to PEP-360

No as PEP 360 is about listing modules where the maintainers asked people to file issues in another issue tracker, submit PRs somewhere else, etc. I am not aware of zoneinfo being developed that way, so I don't think there is anything to do here. Plus PEP 360 is not taking any new mdoules, so zoneinfo is expected to manage issues as reported in Python's issue tracker, PRs merged in the CPython repo, etc.

> even though venv/includepip pulls in I feel like pip/setuptools could/should be there too

They are not part of the stdlib so they do not fall under the purview of any PEPs.

**Comment by warsaw** [comment]
* [PR to make importlib.metadata non-provisional](https://github.com/python/cpython/pull/27101)

**Comment by asottile** [comment]
I once again ask that the rate of change in importlib-* be slowed down

mass changes to the importlib-* modules are being made again with aggressive deprecation breaking interfaces which are widely adopted by the community

the new apis are not better than the existing apis and are creating a lot of churn for developers

again, I advocated heavily for the adoption of these because I believed them to be best for the community -- but a constant cycling of api interfaces because "new shiny thing" does not help the community it causes a lot of toil

the most recent frustration is the deprecation warnings from all of the existing importlib-resources apis now that files() has been introduced.  these are in use by hundreds of packages throughout the community and **there is no good migration pathway without reintroducing backport packages** which is unacceptable complexity.  (I especially wouldn't want to reintroduce the backport packages giving the extremely aggressive rate at which the api is being broken)

@brettcannon can you reopen this for reconsideration -- I think this is important for the python community as a whole given how important the import machinery is

```
open_binary is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.']
```

**Comment by pganssle** [comment]
I am not sure that `zoneinfo` primary development really happens externally, by the way. It hasn't needed much change since the release and it's easier to accept bigger changes on the backport repo because the CI is better there (and the licensing on the backport side is a bit clearer when the contributor explicitly grants the apache license), but long term I'm not sure this is the best workflow.

I've mainly gotten away with not making any firm policies here because the volume has been so low. Good thing I write such flawless software 😛

**Comment by FFY00** [comment]
*sigh* It's not, deprecation and removal are different things, please re-read my reply, particularly the second paragraph. I am probably gonna opt-out of this conversation for now.

**Comment by pablogsal** [comment]
@asottile @pganssle @FFY00 Thanks for opening this issue and communicating your concerns and thoughts.

I will add this to our agenda, but please be aware that unfortunately we have a lot of pending things on it. We will try to get to this ad soon as we can thought.

In any case, please, the SC issue tracker is not the best discusion forum to discuss about this. Many people are not monitoring this issue tracker and this makes it more difficult to keep track. Please, move any constructive discussion to one of the official forums such as python-dev, discourse or BPO.

Thanks for your understanding

**Comment by warsaw** [comment]
Just a point of clarification, because this discussion should be moved to a more appropriate forum.  Quoting:

> Changed in version 3.10: importlib.metadata is no longer provisional.
