### ISSUE TITLE
Submission for SC consideration: Clarification on PEP-609

### ISSUE THREAD

**Issue by gaborbernat** [python/steering-council#70]
Hello, recently I've been talking with @pfmoore and realized that he and @brettcannon have differing interpretations on PEP-609; namely:

Within [this topic](https://discuss.python.org/t/pep-660-editable-installs-for-pep-517-style-build-backends/8510/154) Brett concludes PyPA members don't need a sponsor (or can self-sponsor) PEPs related to Python packaging. However Paul thinks:

> I'm not sure I'd interpret it that way but he's a SC member... I guess you could mark it as self sponsored and see if the PEP editors object... The thing is, the PEP process is owned by the SC, not by PyPA.

I'd like to ask the SC to clarify if the conclusion drawn by @brettcannon is correct, and if so I'd like to update PEP-609 to explicitly state this.

**Comment by warsaw** [comment]
If I read PEP 609 and PEP 1 strictly, I'd say that except for the explicitly named standing delegations, sponsorship is still required for non Python core dev authored packaging PEPs.  However, I'm also pretty sure the SC would likely rubber stamp (or at least not veto) any sponsorship endorsed by the PyPA governors.

**Comment by pfmoore** [comment]
@warsaw if the PyPA were to agree that we were OK with PyPA committers being allowed to sponsor PEPs related to PyPA specifications, would the SC be comfortable with providing a blanket approval for that? If so, then I think the simplest solution would be to add a note to https://www.pypa.io/en/latest/specifications/ or maybe to PEP 609, clarifying that for PEPs related to PyPA specifications, PyPA committers can self-sponsor. Such a change would require a PyPA vote, so that would act as the endorsement you want, without needing it to happen on a case by case basis.

**Comment by warsaw** [comment]
I can't speak for the entire SC, but I would be fine with that.  I'd recommend adding this to PEP 609 for better visibility.

**Comment by gaborbernat** [comment]
If the SC would talk over this at the next meeting and give their approval on it I think the PyPA would be happy to initiate the process to apply and document this change. Does that sound good?

**Comment by warsaw** [comment]
I've put it on the agenda, but we have a packed one so we'll do what we can!

**Comment by brettcannon** [comment]
We discussed this and the decision was that PyPA members can be sponsors for packaging PEPs. Just as a reminder, sponsors are expected to help people through the PEP process, make sure the PEP meets guidelines, and to review PRs for the PEP.

**Comment by gaborbernat** [comment]
Just to clarify, who will be doing the merge on such PRs when the sponsor is not a CPython developer?

**Comment by encukou** [comment]
A [PEP editor](https://www.python.org/dev/peps/pep-0001/#pep-editor-responsibilities-workflow).
