### ISSUE TITLE
A social and private discord chat server for python core-dev

### ISSUE THREAD

**Issue by orsenthil** [python/steering-council#72]
After the Language summit in May 2021, I desired having a dedicated chat server will be beneficial to core-dev. 

I took this idea to vote. 

https://discuss.python.org/t/vote-on-core-dev-chat-choice/8870

The proposal was

1. A new chat server for Python Core-Dev. It will be private to people who fit the definition of core-developer[1]. 

2. It will be for social / team chat. Python-dev has IRC which developers like, and is maintained. The new chat service should be complementary, as it is private, and shouldn't replace, or prioritize over any public discussion channels.

3. After core-dev voting, the proposal will be shared with steering-council. The steering-council can make suggestions and finally pronounce on the topic.

The result of the vote is - https://discuss.python.org/t/vote-on-core-dev-chat-choice/8870/7

 * 34 core-devs participated
 * 87% of us felt we could experiment with something new.
 * 82% of us have voted for a Discord Server.

Steering Council Members, please pronounce on this topic.

1. Should we implement this? 
2. Does steering council have any suggestions?

If we choose to go, I volunteer to create a server, but other core-developers have expressed interest too.

Thank. you!

---- 

[1] For the definition of Core Developer, I think, it reasonable to adopt the [suggestion formulated](https://www.europython-society.org/core-grant/) by EuroPython.

Github “Python core” group members:
    https://github.com/orgs/python/teams/python-core/members
Python Dev Guide Log:
    https://devguide.python.org/developers/
Python Dev Guide Experts Index:
    https://devguide.python.org/experts/

**Comment by Yhg1s** [comment]
As it happens I set something up already, it's just a matter of getting the invite to the right people.

**Comment by orsenthil** [comment]
Hi Thomas, you could add me as an admin. I could help invite the right people.

**Comment by Yhg1s** [comment]
I sent you an invite on discord last week. Also see https://discuss.python.org/t/core-dev-discord/9812

**Comment by brettcannon** [comment]
Since this is now done I am going to close this.
