### ISSUE TITLE
Request for deprecation exception for PyCode_New and PyCode_NewWithPosOnlyArgs

### ISSUE THREAD

**Issue by gvanrossum** [python/steering-council#75]
Code objects are inherently internal details of the CPython implementation. There are some public APIs but they are inherently unstable.

In particular, there are these two APIs:

- `PyCode_New` (with 15 arguments)
- `PyCode_NewWithPosOnlyArgs` (with 16 arguments)

that can be used to create code objects from scratch.

In practice, almost nobody does this except CPython itself. We've found one user, Cython, who pass dummy arguments for almost everything, in order to create a dummy code object. They would be better off with a function `PyCode_NewEmpty` with a few parameters (e.g. name, qualname, filename, firstlineno).

A few other users take an existing code object and create a new one from that with e.g. a modified filename. These users are better off calling the Python-level API `code.replace()`.

So the ideal future state is that both `PyCode_New` and `PyCode_NewWithPosOnlyArgs` are removed from the CPython API, and a new function, `PyCode_NewEmpty` exists to create a dummy code object (calling it would immediately return). (We could also add a C-level API to modify those fields, but it's easy enough to just call the Python-level `.replace()` method from C -- and that's fully backwards compatible for fields like name or filename.)

If we follow the rules of PEP 387 we'd have to keep these two functions around, in deprecated form, in 3.11 and 3.12, so we can delete them in 3.13. But their argument lists map 1-1 to many internal fields, and we are changing some of those fields dramatically -- for example, we've added several new "table" arguments to support zero-overhead exceptions and improved tracebacks (PEP 657).

(In the main branch those were already added as extra arguments, but that's not backwards compatible.)

There has been an extensive discussion about this on python-dev, and the conclusion appears that it's better to just get an exception from the SC instead of trying to craft a crippled backwards compatible version that makes nobody happy -- as always, Cython is happy to check for the version number for this.

**Comment by gvanrossum** [comment]
Discussion:

- (python-committers) https://mail.python.org/archives/list/python-committers@python.org/thread/WZQIL3GLGO7NYC4XHBVFBHUNUJV6NWLE/#BS2L3MDXK232Z523NTIM55ANSDRHR7VJ
- (python-dev) https://mail.python.org/archives/list/python-dev@python.org/thread/ZWTBR5ESYR26BUIVMXOKPFRLGGYDJSFC/#ZWTBR5ESYR26BUIVMXOKPFRLGGYDJSFC

(I apologize for confusing PEP 387 with the Stable ABI, not once, but twice in the above threads. These APIs are not in the Stable ABI or in the Limited API. But we still need an exception.)

**Comment by warsaw** [comment]
@gvanrossum Have you been in contact with the Cython folks?

**Comment by gvanrossum** [comment]
Yes, see this message in the python-dev thread from Stefan Behnel:
https://mail.python.org/archives/list/python-dev@python.org/message/XYNNMH57O7CYWHYKTD3ELZTM3B4M53HL/

**Comment by warsaw** [comment]
Thanks @gvanrossum 

The Steering Council has considered the request and approves of the exception.
