### ISSUE TITLE
Submission for SC consideration: PEP 663 - Enum str(), format(), and repr() changes

### ISSUE THREAD

**Issue by ethanfurman** [python/steering-council#76]
A review of this PEP would be greatly appreciated, particularly with its type (currently informational), and with its backwards compatibility statement:

    Backwards compatibility of stringified objects is not guaranteed across major
    Python versions, and there will be backwards compatibility breaks where

Please let me know if either of those two should be changed.

**Comment by warsaw** [comment]
@ethanfurman While the SC continues to deliberate PEP 663, I have a question: was the PEP applied to 3.11a0+ accidentally?  https://bugs.python.org/issue45493

**Comment by ethanfurman** [comment]
I did update the PEP by splitting the two huge tables into four (hopefully) easier to read tables.

**Comment by ethanfurman** [comment]
Going back to look at the current state of Enum in 3.11, it quickly became apparent that what is there is neither 3.10, nor PEP 663 -- the changes I was finally happy with never made it to code, and the push became getting 3.10 reverted, and then writing PEP 663, and I forgot that 3.11 was in a kind of limbo.

**Comment by warsaw** [comment]
The Steering Council has [rejected PEP 663](https://mail.python.org/archives/list/python-dev@python.org/thread/RN3WCRZSTQR55DOHJTZ2KIO6CZPJPCU7/).
