### ISSUE TITLE
Request for PEP 387 exception: Py_SET_TYPE

### ISSUE THREAD

**Issue by encukou** [python/steering-council#79]
In Python 3.11.0a1, the `Py_TYPE` macro was changed to a function, meaning that it cannot be used as a r-value (i.e. assignment target). All C code of the forms:

    Py_TYPE(obj) = new_type;
    obj->ob_type = new_type;

must be converted to

    Py_SET_TYPE(obj, new_type);

This is documented in [What's New in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html#id2)
The `Py_SET_TYPE` function was  added in Python 3.9.

This change breaks existing code (though many popular projects have already been adapted in the 3.9-3.10 development window).
The change did not follow the process in [PEP 387 -- Backwards Compatibility Policy](https://www.python.org/dev/peps/pep-0387/), which calls for a warning for at least two releases before things break. Unfortunately, it is not feasible to *only* emit a warning when the macro is used as an assignment target.

The reasons for the change are given in [a thread on capi-sig](https://mail.python.org/archives/list/capi-sig@python.org/thread/WGRLTHTHC32DQTACPPX36TPR2GLJAFRB/), specifically:
* [comment on bpo-39573](https://bugs.python.org/issue39573#msg361513)
* [draft PEP 620](https://www.python.org/dev/peps/pep-0620/)
* [an article](https://vstinner.github.io/c-api-abstract-pyobject.html)

I'm not the best person to ask for this exception, as I disagree with making the change now. I believe that:
* the experiments this allows can be run with the patch as part of the experiment;
* third-party extensions needed to validate the experiments can be changed, and they'll usually accept patches if we just *document* that using `Py_TYPE` as r-value is deprecated;
* for third parties, making the change will be easier after 3.8 is EOL and `Py_SET_TYPE` is in all supported Python versions.

I also think that PEP 387 says pretty clearly that exceptions from the policy need a Steering Council exception, but couldn't reach a friendly agreement on that :(
So, here we are: Please consider the change.

**Comment by vstinner** [comment]
See also https://www.python.org/dev/peps/pep-0670/ which is not directly related.

**Comment by encukou** [comment]
PEP 670 was just updated to explicitly say it's not related.

**Comment by pablogsal** [comment]
Thanks for the request @encukou.

After deliberating over this, the Steering Council has agreed that the aforementioned changes to `PY_TYPE` can stay in the 3.11 release. This decision is based on the fact that is not possible to reliably add compiler/preprocessor warnings to the macro and that the impact of this change should be limited (and the fix is not very complex).

Being said that, we also want to add the following:

* If this change results in a severe enough disruption to the community (and therefore our initial assessment about the impact of the change is wrong), the authors of the changes (@vstinner) must be prepared to revert the change before the first beta, given notice from the Steering Council.
* We understand that announcing these changes is challenging given that there is no easy way to add automatic deprecation warnings, but we still believe these changes must be announced better and in general the deprecation notice needs to stay for at least two releases in the documentation.

**Comment by pablogsal** [comment]
Please, feel free to reopen this issue if there is something missing or anything you would like to further discuss.

**Comment by encukou** [comment]
I do.

Apparently there is a [lot of other macros](https://github.com/python/cpython/pull/28976) that are also being converted now. Does this decision apply to all of these? And for any future ones?

Also:

>  these changes must be announced better and in general the deprecation notice needs to stay for at least two releases in the documentation.

There is currently no deprecation warning for this change. What do you mean by "the deprecation notice"? (The closest I can find is a silent documentation change between [3.9](https://docs.python.org/3.9/c-api/structures.html?highlight=py_type#c.Py_TYPE) and [3.10](https://docs.python.org/3.10/c-api/structures.html?highlight=py_type#c.Py_TYPE), and a What's New entry for 3.11.)
Should a notice be added now and stay until 3.12, or should it have been added in 3.9?

**Comment by encukou** [comment]
(I don't have the permisson to reopen the issue.)

**Comment by pablogsal** [comment]
(Reopened)

**Comment by pablogsal** [comment]
> Apparently there is a [lot of other macros](https://github.com/python/cpython/pull/28976) that are also being converted now. Does this decision apply to all of these? And for any future ones?

This decision only applies to `Py_SET_TYPE`

**Comment by pablogsal** [comment]
> There is currently no deprecation warning for this change. What do you mean by "the deprecation notice"? (The closest I can find is a silent documentation change between [3.9](https://docs.python.org/3.9/c-api/structures.html?highlight=py_type#c.Py_TYPE) and [3.10](https://docs.python.org/3.10/c-api/structures.html?highlight=py_type#c.Py_TYPE), and a What's New entry for 3.11.)
> Should a notice be added now and stay until 3.12, or should it have been added in 3.9?

We mean that in general (not for this change as we have made an exception per our previous argument), there should be a deprecation notice in some way or form (in these cases must be in the docs/what's new as there is no way to make the preprocessor warn only when we need it). We just wanted to reiterate that in general, we still want two releases with some deprecation notice for any deprecation, unless exempt.

> Should a notice be added now and stay until 3.12, or should it have been added in 3.9?

For this case, just the What's New entry for 3.11.

**Comment by encukou** [comment]
Thanks for the clarifications!
