### ISSUE TITLE
Submission for SC consideration: PEP 670 -- Convert macros to functions in the Python C API

### ISSUE THREAD

**Issue by vstinner** [python/steering-council#90]
Hi,

The [PEP 670 "Convert macros to functions in the Python C API"](https://www.python.org/dev/peps/pep-0670/#examples-of-macro-pitfalls) has been discussed for 1 month on python-dev. Erlend and me updated the PEP multiple times to address comments of Antoine Pitrou and Petr Viktorin.

The PEP is also based on past discussions on the bug tracker and pull requests. I tried to reply to arguments of Marc Andre Lemburg and Raymond Hettinger, and I added "Rejected Ideas: Keep macros, but fix some macro issues" which tries to describe Lemburg's point of view. I included benchmarks to answer to Raymond's worries about a possible performance slowdown.

Victor and Erlend @erlend-aasland

**Comment by vstinner** [comment]
python-dev thread: https://mail.python.org/archives/list/python-dev@python.org/thread/2GN646CGWGTO6ZHHU7JTA5XWDF4ULM77/

**Comment by brettcannon** [comment]
I've added this to our rolling agenda.

**Comment by vstinner** [comment]
> I've added this to our rolling agenda.

Hi, is there any update on this PEP?

**Comment by pablogsal** [comment]
> > I've added this to our rolling agenda.
> 
> Hi, is there any update on this PEP?

No but is scheduled to be discussed next week.

**Comment by vstinner** [comment]
Hi, did you discuss this PEP in latest meetings? Do you have questions about it?

**Comment by brettcannon** [comment]
We did discuss it, but we aren't done yet.

**Comment by vstinner** [comment]
One of my motivation to push the PEP 670 is my plan to [Slowly bend the C API towards the limited API to get a stable ABI for everyone](https://mail.python.org/archives/list/python-dev@python.org/thread/DN6JAK62ZXZUXQK4MTGYOFEC67XFQYI5/). I didn't put it in the PEP because the relationship between the PEP 670 and the limited API/stable ABI is indirect, and the PEP alone is not enough to immediately make the whole default C API usable to get the stable ABI.

**Comment by erlend-aasland** [comment]
The SC posted an announcement on python-dev recently:

https://mail.python.org/archives/list/python-dev@python.org/message/IJ3IBVY3JDPROKX55YNDT6XZTVTTPGOP/

**Comment by brettcannon** [comment]
I've put the PEP back on our agenda.

**Comment by encukou** [comment]
The PEP is ~~Accepted~~ Final now, I just forgot to close the issue.
Acceptance mail: https://mail.python.org/archives/list/python-dev@python.org/thread/QQFCJ7LR36RUZSC3WI6WZZMQVQ3ZI4MS/
