### ISSUE TITLE
A change of wording in PEP 654 - ExceptionGroups and except*

### ISSUE THREAD

**Issue by iritkatriel** [python/steering-council#94]
Following a review of the PEP-654 documentation, we would like to make a change in the wording of the PEP to clarify that the factory function that automatically selects between ExceptionGroup and BaseExceptionGroup is in fact the BaseExceptionGroup constructor. Please see the proposed change here:   https://github.com/python/peps/pull/2203

@gvanrossum @1st1

**Comment by warsaw** [comment]
This was discussed over in https://github.com/python/cpython/pull/30158

I mentioned that there was a slight difference between the wording of the PEP, which at least to me implied a separate factory function, and the documentation in the above PR.  The discussions over there made it clear that the intention of the API was for the wording in the docs, but as the PEP was what was approved by the 2021 SC, I felt it was necessary for approval from the 2022 SC.

**Comment by Yhg1s** [comment]
I've added it to the SC agenda.

**Comment by Yhg1s** [comment]
The SC approves the wording change. (I've left a comment in the PR as well.)
