### ISSUE TITLE
Submission for SC consideration: PEP 673 -- Self Type

### ISSUE THREAD

**Issue by pradeep90** [python/steering-council#95]
Please consider PEP 673 for inclusion in Python 3.11. This is primarily of interest to users of static type checkers. It provides a simple and intuitive way to annotate methods that accept or return an instance of their class.

The PEP has been discussed at length in [typing sig](https://mail.python.org/archives/list/typing-sig@python.org/thread/SJAANGA2CWZ6D6TJ7KOPG7PZQC56K73S/#SJAANGA2CWZ6D6TJ7KOPG7PZQC56K73S) and on the [draft doc](https://docs.google.com/document/d/1ujuSMXDmSIOJpiZyV7mvBEC8P-y55AgSzXcvhrZciuI/edit). We have also notified [python-dev](https://mail.python.org/archives/list/python-dev@python.org/message/G4F3ZMCJRWWRSF7O34Z7RPYQQK7QPGB6/).

There are reference implementations of the type checking part in Pyright and Mypy. There is also an [implementation](https://github.com/python/typing/pull/933) of the `Self` special form in `typing_extensions.py`.

CC: @Gobot1234 @JelleZijlstra

https://www.python.org/dev/peps/pep-0673/

**Comment by brettcannon** [comment]
Thanks! I will add it to our review queue.

**Comment by encukou** [comment]
Accepted in https://mail.python.org/archives/list/python-dev@python.org/thread/J7BWL5KWOPQQK5KFWKENVLXW6UGSPTGI/
Congratulations!
