### ISSUE TITLE
 Submission for SC consideration: PEP 677 -- Callable Type Syntax

### ISSUE THREAD

**Issue by stroxler** [python/steering-council#98]
Please consider PEP 677.

This is primarily of interest to users of type checking. It provides a concise way to annotate callable types using an arrow syntax inspired by function headers (and the syntax used by other languages like Typescript and Kotlin).

The PEP has been discussed at length in typing-sig and python-dev.

Since there are many discussions about this, here's a quick summary with links to key threads:
- In typing-sig [[1]](https://mail.python.org/archives/list/typing-sig@python.org/thread/ATE7XWMKKS6E7HE7HUNY7RFJTQADWRBQ/#S77V44FAMNHUY7EX3QSUYBCCWVUZ4XBS) [[2]](https://mail.python.org/archives/list/typing-sig@python.org/message/RFZOSCJHDS66MOVQO6XMVVX43VEKJJBW/) there is strong support for this PEP.
  - About 2/3 of typing-sig would have preferred complex syntax supporting named, optional, and variadic args.
    - We discuss this idea in some detail as "Extended Syntax" in our Rejected Alternatives section.
    - We've confirmed that the current proposal is forward-compatible with extended syntax.
  - We proposed this simpler PEP partly because opinions were mixed, but also following [guidance in PEP1](https://www.python.org/dev/peps/pep-0001/#id16) to prefer breaking complex changes into focused PEPs.
- In python-dev [[1]](https://mail.python.org/archives/list/python-dev@python.org/thread/OGACYN2X7RX2GHAUP2AKRPT6DP432VCN/) [[2]](https://mail.python.org/archives/list/python-dev@python.org/thread/GQB36XDSPIJBAPBQCYVNVPGXS4W2NZA2/). Opinions are mixed.
  - The most detailed critique is [this](https://mail.python.org/archives/list/python-dev@python.org/thread/FI4AFU3I25PECARIH2EVKAD5C5RJRE2N/) by @isidentical.

CC @pradeep90 @gvanrossum 

https://www.python.org/dev/peps/pep-0677/

**Comment by encukou** [comment]
Thanks! I added it to the SC agenda.

**Comment by gpshead** [comment]
We decided to reject this PEP. Rationale and discussion over in https://mail.python.org/archives/list/python-dev@python.org/thread/NHCLHCU2XCWTBGF732WESMN42YYVKOXB/
