### ISSUE TITLE
Request for SC Comment: How to proceed with applying PEP 630 (Isolating Modules) in the CPython standard library

### ISSUE THREAD

**Issue by erlend-aasland** [python/steering-council#99]
As of [2021-02-08, the SC halted](https://github.com/python/steering-council/blob/1d85eefdc5861a096c3859e9990dbc8527c5973b/updates/2021-02-steering-council-update.md) module state (and sub-interpreter related) changes with the following statement:

_The Steering Council discussed the ongoing work on porting types in the standard library to heap-types and the subinterpreter-related changes. It was decided that through Pablo, the Steering Council will ask the core developers driving those changes to create an informational PEP and not to make any more changes in this area after beta 1, as per our general policy._

In order to resolve the current deadlocked situation, there is an effort over at Petrs [abi3 repo](https://github.com/encukou/abi3/issues/21) to create a fairly informal document that describes how one should proceed when isolating modules in the standard library.

My question for the SC is: Is it the SC's opinion that a more formal document, for example an inform(ation)al[^1] PEP, is still required, or would a section in the devguide (or a similar stand-alone document) be sufficient?

[^1]: formal/informal pun intended

**Comment by brettcannon** [comment]
I've added this to our agenda.

Off-topic: issue 99!

**Comment by vstinner** [comment]
Last October, the PEP 630 and an hypothetical new PEP was discussed in https://bugs.python.org/issue45113

**Comment by encukou** [comment]
Here's my update to PEP 630: https://github.com/python/peps/pull/2319

I'd like to apologize to everyone who was misled by the previous version of this PEP.

**Comment by encukou** [comment]
Thanks to the increased visibility of the issue(s) I was hopefully able to clear some of the misunderstandings around isolating modules in the standard library. I've just updated PEP 630, and I'll work on a write-up that should be more understandable to the SC.

Meanwhile, let me close this issue. It is not ready yet. If the SC or anyone else wants to discuss it, contact me directly or [here](https://github.com/encukou/abi3/issues/21#issuecomment-1039233188).
